<a href="https://colab.research.google.com/github/eltahir64-spec/Agentic-AI-memory-Implementation/blob/main/Copy_of_NIMS_ICS_compliant_incident_action_plan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Create a Python script that generates NIMS/ICS compliant Incident Action Plans (IAPs) by interactively prompting the user for all necessary information and then outputting a formatted IAP document.

## Research NIMS/ICS IAP Structure

### Subtask:
Begin by researching the essential components and required information for a NIMS/ICS compliant Incident Action Plan (IAP) to ensure all necessary fields and sections are included in the generated output.


### Researching NIMS/ICS IAP Structure

To ensure the generated Incident Action Plan (IAP) is NIMS/ICS compliant, we will begin by researching the essential components and required information. This involves reviewing official documentation to identify all necessary fields and sections.

**Instructions:**
1.  **Search for Official Documentation:** Locate and review official NIMS/ICS (National Incident Management System/Incident Command System) documentation specifically related to Incident Action Plans (IAPs).
2.  **Identify Core Sections:** Pinpoint the fundamental sections and elements that are mandatory for a compliant IAP. Examples include, but are not limited to, Incident Objectives, Organization Assignment List, Communications Plan, Medical Plan, and Traffic Plan.
3.  **Note Specific Fields:** Pay close attention to any particular data points or fields required within each identified section (e.g., incident name, operational period, preparer, resources assigned, special instructions).
4.  **Compile Comprehensive List:** Create a detailed list of all required fields and sections. This compilation will serve as the foundation for the IAP data model, guiding what information needs to be collected and subsequently included in the final IAP document.

### Essential Components of a NIMS/ICS Incident Action Plan (IAP)

Based on NIMS/ICS guidelines (e.g., ICS Form 201, 202, 203, 204, 205, 206), a compliant Incident Action Plan (IAP) typically includes the following core sections and essential information:

**1. ICS Form 202 - Incident Objectives:**
*   **Incident Name:** Official name of the incident.
*   **Operational Period:** Start and end date/time for which the IAP is valid.
*   **General Objectives:** Overarching incident goals (safety, life safety, incident stabilization, property/environmental conservation).
*   **Specific Objectives:** Measurable, actionable, time-sensitive objectives for the operational period.
*   **Approval/Preparer Information:** Name and position of preparer, date/time prepared.

**2. ICS Form 203 - Organization Assignment List (OAL):**
*   **Incident Management Team (IMT) Structure:** Names and assignments for key ICS positions (Incident Commander, Command Staff, General Staff).
*   **Reporting Relationships:** Clear lines of authority and communication.

**3. ICS Form 204 - Assignment List:**
*   **Branch/Division/Group:** Specific operational areas.
*   **Leader:** Name of the assigned leader for the operational area.
*   **Resources Assigned:** List of personnel and equipment assigned.
*   **Work Assignments:** Specific tasks and tactics for the operational period.
*   **Special Instructions:** Any additional guidance or safety considerations.
*   **Reporting Location/Time:** Where and when resources should report.

**4. ICS Form 205 - Incident Radio Communications Plan:**
*   **Operational Period:** Dates and times.
*   **Radio System Information:** Type of system (e.g., analog, digital).
*   **Channel Assignments:** Primary, tactical, support, air-to-ground frequencies.
*   **Call Signs:** Assigned identifiers for various units.
*   **Remarks:** Any special communication procedures.

**5. ICS Form 206 - Medical Plan:**
*   **Operational Period:** Dates and times.
*   **Medical Aid Stations:** Locations and capabilities.
*   **Ambulance Exchange Points:** Designated points for patient transfer.
*   **Hospitals/Clinics:** Names, locations, contact info, and specializations.
*   **Medical Emergency Procedures:** Steps to take in case of an injury.

**6. Other Supporting Documents/Information (often attached or integrated):**
*   **Incident Map:** Depicting incident area, resources, hazards, and tactical assignments.
*   **Safety Plan (ICS 208):** Hazard analysis, safety message, control measures.
*   **Traffic Plan (if applicable):** Traffic flow, control points, access routes.
*   **Site Safety and Health Plan (SSHP):** Detailed safety procedures for hazardous materials incidents.
*   **Resource List (ICS 209/211):** Summary of all assigned resources.
*   **Weather Forecast:** Relevant weather information for the operational period.

This summary provides the foundational elements to build a comprehensive data model for an IAP, ensuring all critical information is collected and presented according to NIMS/ICS standards.

## Define IAP Data Model

### Subtask:
Based on the NIMS/ICS research, define a Python data structure (e.g., a dictionary or a class) that will hold all the necessary information for the Incident Action Plan. This will serve as the template for collecting data.


**Reasoning**:
The subtask requires defining a Python data structure for the Incident Action Plan (IAP) based on NIMS/ICS research. A nested dictionary is a suitable choice for organizing the various sections and their fields, accommodating multiple entries where necessary. The next step is to create this dictionary structure with placeholders.



In [ ]:
iap_data_model = {
    "Incident_Name": None,
    "Operational_Period": {
        "Start_Date": None,
        "End_Date": None,
        "Start_Time": None,
        "End_Time": None
    },
    "ICS_202_Incident_Objectives": {
        "Objectives": [],
        "General_Safety_Message": None,
        "Prepared_By": {
            "Name": None,
            "Position": None,
            "Signature": None
        },
        "Date": None,
        "Time": None
    },
    "ICS_203_Organization_Assignment_List": {
        "Incident_Commander": {
            "Name": None,
            "Agency": None,
            "Phone": None
        },
        "Section_Chiefs": {
            "Operations": {"Name": None, "Agency": None, "Phone": None},
            "Planning": {"Name": None, "Agency": None, "Phone": None},
            "Logistics": {"Name": None, "Agency": None, "Phone": None},
            "Finance_Admin": {"Name": None, "Agency": None, "Phone": None}
        },
        "Other_Positions": [] # List of dictionaries for other key positions
    },
    "ICS_204_Assignment_List": [
        # Each item in this list will be a dictionary representing one assignment
        {
            "Division_Group": None,
            "Branch": None,
            "Resources_Assigned": [], # List of dictionaries for resources (e.g., {'Name': 'Engine 1', 'Type': 'Fire Engine'})
            "Task_Activity": None,
            "Special_Instructions": None,
            "Reporting_Location": None,
            "Reporting_Time": None,
            "Supervisor": {"Name": None, "Contact": None}
        }
    ],
    "ICS_205_Incident_Radio_Communications_Plan": [
        # Each item in this list will be a dictionary representing one channel
        {
            "Channel_Name": None,
            "Function": None,
            "Assignment": None,
            "Frequency_Mode_Tone": None,
            "Remarks": None
        }
    ],
    "ICS_206_Medical_Plan": {
        "Medical_Aid_Stations": [],
        "Hospitals": [],
        "Ambulance_Services": [],
        "Medical_Emergency_Procedures": None
    },
    "Map_Diagram": {
        "Description": None,
        "File_Path": None # Placeholder for a file path or URL to a map/diagram
    },
    "Safety_Message_Plan": None # Could be a string or a more structured dictionary
}

print("IAP Data Model Structure:\n")
import json
print(json.dumps(iap_data_model, indent=4))


IAP Data Model Structure:

{
    "Incident_Name": null,
    "Operational_Period": {
        "Start_Date": null,
        "End_Date": null,
        "Start_Time": null,
        "End_Time": null
    },
    "ICS_202_Incident_Objectives": {
        "Objectives": [],
        "General_Safety_Message": null,
        "Prepared_By": {
            "Name": null,
            "Position": null,
            "Signature": null
        },
        "Date": null,
        "Time": null
    },
    "ICS_203_Organization_Assignment_List": {
        "Incident_Commander": {
            "Name": null,
            "Agency": null,
            "Phone": null
        },
        "Section_Chiefs": {
            "Operations": {
                "Name": null,
                "Agency": null,
                "Phone": null
            },
            "Planning": {
                "Name": null,
                "Agency": null,
                "Phone": null
            },
            "Logistics": {
                "Name": null,
     

## Develop Interactive Input Script

### Subtask:
Create a Python script that interactively prompts the user for all the required information for the Incident Action Plan, following the defined data model. This script should be user-friendly and guide the user through the data entry process.


**Reasoning**:
The subtask requires creating a Python script that interactively prompts the user for IAP information based on the `iap_data_model`. I will start by defining helper functions to handle different types of inputs (strings, dates/times, lists of items, and nested dictionaries) to make the main data collection function more modular and readable. This approach aligns with the instructions to create a user-friendly and guided data entry process.



In [ ]:
import json
import datetime

def get_string_input(prompt, default=None):
    """Gets a string input from the user."""
    while True:
        value = input(prompt).strip()
        if value or default is not None:
            return value if value else default
        print("Input cannot be empty. Please provide a value.")

def get_datetime_input(prompt, format_str, value_type="date"):
    """Gets a date or time input from the user with validation."""
    while True:
        user_input = input(prompt).strip()
        if not user_input: # Allow empty input for optional fields
            return None
        try:
            if value_type == "date":
                return datetime.datetime.strptime(user_input, format_str).strftime('%Y-%m-%d')
            elif value_type == "time":
                return datetime.datetime.strptime(user_input, format_str).strftime('%H:%M')
            else:
                raise ValueError("Invalid value_type for get_datetime_input")
        except ValueError:
            print(f"Invalid format. Please use {format_str}.")

def get_list_of_dicts_input(prompt_singular, field_definitions):
    """Collects multiple entries, each a dictionary, for a list type field."""
    items = []
    print(f"\n--- Collecting {prompt_singular}s ---")
    while True:
        print(f"Enter details for a new {prompt_singular} (or type 'done' to finish):")
        temp_dict = {}
        is_done = False

        # Check if user wants to stop before collecting any fields for the current item
        check_done = input(f"    (Type 'done' or press Enter to add a {prompt_singular}): ").strip().lower()
        if check_done == 'done':
            break

        for field_name, field_type_info in field_definitions.items():
            field_type = field_type_info.get('type')
            field_prompt = field_type_info.get('prompt', f"    Enter {prompt_singular} {field_name}: ")
            field_format = field_type_info.get('format_str')

            if field_type == 'string':
                value = get_string_input(field_prompt)
            elif field_type == 'date':
                value = get_datetime_input(field_prompt, field_format, value_type='date')
            elif field_type == 'time':
                value = get_datetime_input(field_prompt, field_format, value_type='time')
            else: # Default to string for unknown types
                value = get_string_input(field_prompt)

            temp_dict[field_name] = value

        if temp_dict: # Only add if at least some fields were filled (user didn't just type 'done' and then nothing)
            items.append(temp_dict)

        # Offer to continue or stop
        if not get_string_input(f"Add another {prompt_singular}? (yes/no): ", default='yes').lower() == 'yes':
            break
    return items

def get_dict_input(prompt, field_definitions):
    """Collects fields for a dictionary type field."""
    print(f"\n--- Collecting {prompt} Details ---")
    data_dict = {}
    for field_name, field_type_info in field_definitions.items():
        field_type = field_type_info.get('type')
        field_prompt = field_type_info.get('prompt', f"    Enter {field_name}: ")
        field_format = field_type_info.get('format_str')

        if field_type == 'string':
            value = get_string_input(field_prompt)
        elif field_type == 'date':
            value = get_datetime_input(field_prompt, field_format, value_type='date')
        elif field_type == 'time':
            value = get_datetime_input(field_prompt, field_format, value_type='time')
        else:
            value = get_string_input(field_prompt)
        data_dict[field_name] = value
    return data_dict

print("Helper functions for interactive input are defined.")

Helper functions for interactive input are defined.


**Reasoning**:
Now that the helper functions are defined, I will implement the main `collect_iap_data` function. This function will iterate through the `iap_data_model` structure, using the previously defined helper functions to interactively prompt the user for all necessary information. It will handle various field types including simple strings, dates, times, nested dictionaries, and lists of dictionaries. Finally, it will call this function and print the collected data to verify its structure.



In [ ]:
def collect_iap_data(data_model):
    """Interactively collects Incident Action Plan data from the user."""
    iap_data = data_model.copy() # Create a mutable copy to populate

    print("\n--- Incident Action Plan Data Collection ---")

    # Incident Name
    iap_data["Incident_Name"] = get_string_input("Enter Incident Name: ")

    # Operational Period
    print("\n--- Operational Period ---")
    iap_data["Operational_Period"]["Start_Date"] = get_datetime_input("Enter Operational Period Start Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["Operational_Period"]["End_Date"] = get_datetime_input("Enter Operational Period End Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["Operational_Period"]["Start_Time"] = get_datetime_input("Enter Operational Period Start Time (HH:MM): ", "%H:%M", "time")
    iap_data["Operational_Period"]["End_Time"] = get_datetime_input("Enter Operational Period End Time (HH:MM): ", "%H:%M", "time")

    # ICS Form 202 - Incident Objectives
    print("\n--- ICS Form 202 - Incident Objectives ---")
    # Objectives - List of strings for simplicity, could be enhanced to list of dicts if more detail needed per obj
    iap_data["ICS_202_Incident_Objectives"]["Objectives"] = []
    print("Enter General Objectives (type 'done' to finish each objective):")
    while True:
        objective = get_string_input("    Objective: ")
        if objective.lower() == 'done':
            break
        if objective: # Only add if not empty
            iap_data["ICS_202_Incident_Objectives"]["Objectives"].append(objective)

    iap_data["ICS_202_Incident_Objectives"]["General_Safety_Message"] = get_string_input("Enter General Safety Message: ")

    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Name"] = get_string_input("Enter Preparer Name: ")
    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Position"] = get_string_input("Enter Preparer Position: ")
    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Signature"] = get_string_input("Enter Preparer Signature (or leave blank): ", default='')
    iap_data["ICS_202_Incident_Objectives"]["Date"] = get_datetime_input("Enter Prepared Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["ICS_202_Incident_Objectives"]["Time"] = get_datetime_input("Enter Prepared Time (HH:MM): ", "%H:%M", "time")

    # ICS Form 203 - Organization Assignment List
    print("\n--- ICS Form 203 - Organization Assignment List ---")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Name"] = get_string_input("Enter Incident Commander Name: ")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Agency"] = get_string_input("Enter Incident Commander Agency: ")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Phone"] = get_string_input("Enter Incident Commander Phone: ")

    for section, details in iap_data["ICS_203_Organization_Assignment_List"]["Section_Chiefs"].items():
        print(f"  --- {section} Section Chief ---")
        details["Name"] = get_string_input(f"    Enter {section} Section Chief Name: ")
        details["Agency"] = get_string_input(f"    Enter {section} Section Chief Agency: ")
        details["Phone"] = get_string_input(f"    Enter {section} Section Chief Phone: ")

    # Other Positions (list of dicts)
    iap_data["ICS_203_Organization_Assignment_List"]["Other_Positions"] = get_list_of_dicts_input(
        "Other Position",
        {
            "Name": {"type": "string", "prompt": "    Enter Name: "},
            "Position": {"type": "string", "prompt": "    Enter Position: "},
            "Agency": {"type": "string", "prompt": "    Enter Agency: "},
            "Phone": {"type": "string", "prompt": "    Enter Phone: "}
        }
    )

    # ICS Form 204 - Assignment List
    iap_data["ICS_204_Assignment_List"] = get_list_of_dicts_input(
        "Assignment",
        {
            "Division_Group": {"type": "string"},
            "Branch": {"type": "string", "prompt": "    Enter Branch (optional, press Enter to skip): ", "default": None},
            "Resources_Assigned": {"type": "list_of_strings", "prompt": "    Enter Resource (e.g., Engine 1, Medic 5 - type 'done' to finish resources): "},
            "Task_Activity": {"type": "string"},
            "Special_Instructions": {"type": "string", "prompt": "    Enter Special Instructions (optional, press Enter to skip): ", "default": None},
            "Reporting_Location": {"type": "string"},
            "Reporting_Time": {"type": "time", "format_str": "%H:%M"},
            "Supervisor_Name": {"type": "string", "prompt": "    Enter Supervisor Name: "},
            "Supervisor_Contact": {"type": "string", "prompt": "    Enter Supervisor Contact: "}
        }
    )
    # Special handling for Resources_Assigned within Assignment List
    for assignment in iap_data["ICS_204_Assignment_List"]:
        resources = []
        print(f"  --- Resources for {assignment.get('Division_Group', 'an assignment')} ---")
        while True:
            resource = get_string_input("    Enter Resource (e.g., Engine 1, Medic 5 - type 'done' to finish): ")
            if resource.lower() == 'done':
                break
            if resource:
                resources.append(resource)
        assignment["Resources_Assigned"] = resources
        # Flatting supervisor details
        assignment["Supervisor"] = {
            "Name": assignment.pop("Supervisor_Name"),
            "Contact": assignment.pop("Supervisor_Contact")
        }

    # ICS Form 205 - Incident Radio Communications Plan
    iap_data["ICS_205_Incident_Radio_Communications_Plan"] = get_list_of_dicts_input(
        "Radio Channel",
        {
            "Channel_Name": {"type": "string"},
            "Function": {"type": "string"},
            "Assignment": {"type": "string"},
            "Frequency_Mode_Tone": {"type": "string"},
            "Remarks": {"type": "string", "prompt": "    Enter Remarks (optional, press Enter to skip): ", "default": None}
        }
    )

    # ICS Form 206 - Medical Plan
    print("\n--- ICS Form 206 - Medical Plan ---")
    iap_data["ICS_206_Medical_Plan"]["Medical_Aid_Stations"] = get_list_of_dicts_input(
        "Medical Aid Station",
        {
            "Name": {"type": "string"},
            "Location": {"type": "string"},
            "Capabilities": {"type": "string"}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Hospitals"] = get_list_of_dicts_input(
        "Hospital",
        {
            "Name": {"type": "string"},
            "Location": {"type": "string"},
            "Contact": {"type": "string"},
            "Specializations": {"type": "string", "prompt": "    Enter Specializations (optional, press Enter to skip): ", "default": None}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Ambulance_Services"] = get_list_of_dicts_input(
        "Ambulance Service",
        {
            "Provider": {"type": "string"},
            "Contact": {"type": "string"},
            "Exchange_Points": {"type": "string", "prompt": "    Enter Exchange Points (optional, press Enter to skip): ", "default": None}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Medical_Emergency_Procedures"] = get_string_input("Enter Medical Emergency Procedures: ")

    # Map/Diagram
    print("\n--- Map / Diagram ---")
    iap_data["Map_Diagram"]["Description"] = get_string_input("Enter Map/Diagram Description (optional, press Enter to skip): ", default=None)
    iap_data["Map_Diagram"]["File_Path"] = get_string_input("Enter Map/Diagram File Path/URL (optional, press Enter to skip): ", default=None)

    # Safety Message/Plan
    iap_data["Safety_Message_Plan"] = get_string_input("Enter Safety Message/Plan details (optional, press Enter to skip): ", default=None)

    return iap_data

# Call the function to collect data
print("Starting interactive IAP data collection. Follow the prompts.")
filled_iap_data = collect_iap_data(iap_data_model)

print("\n--- Collected IAP Data ---")
print(json.dumps(filled_iap_data, indent=4))


Starting interactive IAP data collection. Follow the prompts.

--- Incident Action Plan Data Collection ---

--- Operational Period ---

--- ICS Form 202 - Incident Objectives ---
Enter General Objectives (type 'done' to finish each objective):

--- ICS Form 203 - Organization Assignment List ---
  --- Operations Section Chief ---
  --- Planning Section Chief ---
  --- Logistics Section Chief ---
  --- Finance_Admin Section Chief ---


## Generate Formatted IAP Output

### Subtask:
Implement the Python code to take the data collected from the user and format it into a clear, readable, and NIMS/ICS compliant Incident Action Plan document. The output should be easily consumable, perhaps as a plain text or Markdown file.


**Reasoning**:
The subtask requires generating a formatted IAP document from the collected data. I will define a Python function `generate_iap_document` that takes the `filled_iap_data` and formats it into a Markdown string, handling various data types and nested structures, and then print the result.



In [ ]:
def generate_iap_document(iap_data):
    """Generates a formatted NIMS/ICS compliant Incident Action Plan document from collected data."""
    document_parts = []

    document_parts.append("# Incident Action Plan (IAP)\n")

    if iap_data.get("Incident_Name"):
        document_parts.append(f"## Incident Name: {iap_data['Incident_Name']}\n")

    # Operational Period
    op_period = iap_data.get("Operational_Period")
    if op_period and op_period.get("Start_Date"):
        document_parts.append("### 1. Operational Period\n")
        document_parts.append(f"* **Start:** {op_period.get('Start_Date')} {op_period.get('Start_Time')}\n")
        document_parts.append(f"* **End:** {op_period.get('End_Date')} {op_period.get('End_Time')}\n\n")

    # ICS 202 - Incident Objectives
    ics_202 = iap_data.get("ICS_202_Incident_Objectives")
    if ics_202 and (ics_202.get("Objectives") or ics_202.get("General_Safety_Message")):
        document_parts.append("### 2. ICS Form 202 - Incident Objectives\n")
        if ics_202.get("Objectives"):
            document_parts.append("#### Objectives:\n")
            for obj in ics_202["Objectives"]:
                document_parts.append(f"* {obj}\n")
        if ics_202.get("General_Safety_Message"):
            document_parts.append(f"#### General Safety Message:\n{ics_202['General_Safety_Message']}\n")
        if ics_202.get("Prepared_By") and ics_202["Prepared_By"].get("Name"):
            prep = ics_202["Prepared_By"]
            document_parts.append(f"* **Prepared By:** {prep.get('Name')} ({prep.get('Position')})\n")
            if prep.get('Signature'):
                document_parts.append(f"* **Signature:** {prep.get('Signature')}\n")
            document_parts.append(f"* **Date/Time:** {ics_202.get('Date')} {ics_202.get('Time')}\n\n")

    # ICS 203 - Organization Assignment List
    ics_203 = iap_data.get("ICS_203_Organization_Assignment_List")
    if ics_203 and (ics_203.get("Incident_Commander") or ics_203.get("Section_Chiefs") or ics_203.get("Other_Positions")):
        document_parts.append("### 3. ICS Form 203 - Organization Assignment List\n")
        if ics_203.get("Incident_Commander") and ics_203["Incident_Commander"].get("Name"):
            ic = ics_203["Incident_Commander"]
            document_parts.append(f"#### Incident Commander:\n")
            document_parts.append(f"* **Name:** {ic.get('Name')}\n")
            document_parts.append(f"* **Agency:** {ic.get('Agency')}\n")
            document_parts.append(f"* **Phone:** {ic.get('Phone')}\n\n")

        if ics_203.get("Section_Chiefs"):
            document_parts.append("#### Section Chiefs:\n")
            for section, details in ics_203["Section_Chiefs"].items():
                if details.get("Name"):
                    document_parts.append(f"* **{section.replace('_', ' ')}:** {details.get('Name')} ({details.get('Agency')}) - {details.get('Phone')}\n")
            document_parts.append("\n")

        if ics_203.get("Other_Positions"):
            document_parts.append("#### Other Key Positions:\n")
            for pos in ics_203["Other_Positions"]:
                if pos.get("Name"):
                    document_parts.append(f"* **{pos.get('Position')}:** {pos.get('Name')} ({pos.get('Agency')}) - {pos.get('Phone')}\n")
            document_parts.append("\n")

    # ICS 204 - Assignment List
    ics_204_list = iap_data.get("ICS_204_Assignment_List")
    if ics_204_list:
        document_parts.append("### 4. ICS Form 204 - Assignment List\n")
        for i, assignment in enumerate(ics_204_list):
            if assignment.get("Division_Group"):
                document_parts.append(f"#### Assignment {i+1}: {assignment.get('Division_Group')}\n")
                if assignment.get("Branch"):
                    document_parts.append(f"* **Branch:** {assignment.get('Branch')}\n")
                if assignment.get("Resources_Assigned"):
                    document_parts.append(f"* **Resources Assigned:** {', '.join(assignment['Resources_Assigned'])}\n")
                if assignment.get("Task_Activity"):
                    document_parts.append(f"* **Task/Activity:** {assignment.get('Task_Activity')}\n")
                if assignment.get("Special_Instructions"):
                    document_parts.append(f"* **Special Instructions:** {assignment.get('Special_Instructions')}\n")
                if assignment.get("Reporting_Location"):
                    document_parts.append(f"* **Reporting Location:** {assignment.get('Reporting_Location')}\n")
                if assignment.get("Reporting_Time"):
                    document_parts.append(f"* **Reporting Time:** {assignment.get('Reporting_Time')}\n")
                if assignment.get("Supervisor") and assignment["Supervisor"].get("Name"):
                    sup = assignment["Supervisor"]
                    document_parts.append(f"* **Supervisor:** {sup.get('Name')} ({sup.get('Contact')})\n")
                document_parts.append("\n")

    # ICS 205 - Incident Radio Communications Plan
    ics_205_list = iap_data.get("ICS_205_Incident_Radio_Communications_Plan")
    if ics_205_list:
        document_parts.append("### 5. ICS Form 205 - Incident Radio Communications Plan\n")
        for i, channel in enumerate(ics_205_list):
            if channel.get("Channel_Name"):
                document_parts.append(f"#### Channel {i+1}: {channel.get('Channel_Name')}\n")
                document_parts.append(f"* **Function:** {channel.get('Function')}\n")
                document_parts.append(f"* **Assignment:** {channel.get('Assignment')}\n")
                document_parts.append(f"* **Frequency/Mode/Tone:** {channel.get('Frequency_Mode_Tone')}\n")
                if channel.get("Remarks"):
                    document_parts.append(f"* **Remarks:** {channel.get('Remarks')}\n")
                document_parts.append("\n")

    # ICS 206 - Medical Plan
    ics_206 = iap_data.get("ICS_206_Medical_Plan")
    if ics_206 and (ics_206.get("Medical_Aid_Stations") or ics_206.get("Hospitals") or ics_206.get("Ambulance_Services") or ics_206.get("Medical_Emergency_Procedures")):
        document_parts.append("### 6. ICS Form 206 - Medical Plan\n")
        if ics_206.get("Medical_Aid_Stations"):
            document_parts.append("#### Medical Aid Stations:\n")
            for station in ics_206["Medical_Aid_Stations"]:
                if station.get("Name"):
                    document_parts.append(f"* **{station.get('Name')}:** {station.get('Location')} (Capabilities: {station.get('Capabilities')})\n")
            document_parts.append("\n")

        if ics_206.get("Hospitals"):
            document_parts.append("#### Hospitals:\n")
            for hospital in ics_206["Hospitals"]:
                if hospital.get("Name"):
                    specs = f" (Specializations: {hospital['Specializations']})" if hospital.get('Specializations') else ''
                    document_parts.append(f"* **{hospital.get('Name')}:** {hospital.get('Location')} (Contact: {hospital.get('Contact')}){specs}\n")
            document_parts.append("\n")

        if ics_206.get("Ambulance_Services"):
            document_parts.append("#### Ambulance Services:\n")
            for service in ics_206["Ambulance_Services"]:
                if service.get("Provider"):
                    ex_points = f" (Exchange Points: {service['Exchange_Points']})" if service.get('Exchange_Points') else ''
                    document_parts.append(f"* **{service.get('Provider')}:** Contact: {service.get('Contact')}{ex_points}\n")
            document_parts.append("\n")

        if ics_206.get("Medical_Emergency_Procedures"):
            document_parts.append(f"#### Medical Emergency Procedures:\n{ics_206['Medical_Emergency_Procedures']}\n\n")

    # Map/Diagram
    map_diag = iap_data.get("Map_Diagram")
    if map_diag and (map_diag.get("Description") or map_diag.get("File_Path")):
        document_parts.append("### 7. Map / Diagram\n")
        if map_diag.get("Description"):
            document_parts.append(f"* **Description:** {map_diag.get('Description')}\n")
        if map_diag.get("File_Path"):
            document_parts.append(f"* **File Path/URL:** {map_diag.get('File_Path')}\n")
        document_parts.append("\n")

    # Safety Message/Plan
    if iap_data.get("Safety_Message_Plan"):
        document_parts.append("### 8. Safety Message / Plan\n")
        document_parts.append(f"{iap_data['Safety_Message_Plan']}\n\n")

    return "".join(document_parts)

# Generate and print the IAP document
print("\n--- Generated IAP Document ---\n")
formatted_iap_document = generate_iap_document(filled_iap_data)
print(formatted_iap_document)


## Final Task

### Subtask:
Provide the complete Python code for the interactive IAP generator and clear instructions on how to run and use it to create compliant Incident Action Plans.


## Summary:

### Data Analysis Key Findings

*   **Comprehensive NIMS/ICS IAP Structure Identified:** The initial research phase successfully outlined the essential components of a NIMS/ICS compliant Incident Action Plan (IAP). This included detailing information required for core ICS forms such as ICS Form 202 (Incident Objectives), ICS Form 203 (Organization Assignment List), ICS Form 204 (Assignment List), ICS Form 205 (Incident Radio Communications Plan), and ICS Form 206 (Medical Plan). Supporting documents like Incident Maps and Safety Plans were also identified as crucial for a complete IAP.
*   **Robust IAP Data Model Developed:** A comprehensive Python data structure, implemented as a nested dictionary, was created to store all necessary IAP information. This model effectively handles various data types including simple strings, formatted dates and times, nested dictionaries for hierarchical information (e.g., Incident Commander details), and lists of dictionaries for multiple entries (e.g., multiple assignments or radio channels).
*   **Interactive Data Collection Script Implemented:** A user-friendly Python script was developed to interactively prompt the user for all IAP data, guided by the defined data model. The script includes helper functions for robust input validation (e.g., date/time formats) and supports collecting multiple entries for list-type fields, ensuring all required information is gathered systematically.
*   **Formatted IAP Document Generation Capability:** A Python function `generate_iap_document` was created to convert the collected IAP data into a clear, readable, and NIMS/ICS compliant document. This function leverages Markdown formatting for structured output, applying conditional logic to include sections and fields only when data is present, thereby producing a clean and professional document.

### Insights or Next Steps

*   The modular design, separating data model definition, interactive input, and document generation, provides a flexible and maintainable foundation for future enhancements to the IAP generator.
*   Next steps could involve implementing options to save the generated IAP document to various file formats (e.g., `.md`, `.txt`, or even PDF for official use) and incorporating a graphical user interface (GUI) for a more accessible user experience.


# Task
Next, we will enhance the document generation function to save the formatted IAP content to a Markdown (`.md`) file and a plain text (`.txt`) file, in addition to displaying it in the console.

## Enhance Document Output to File

### Subtask:
Modify the document generation function to save the formatted IAP content to a Markdown (.md) file and a plain text (.txt) file, in addition to displaying it in the console.


### Enhance Document Output to File

To enhance the document output, we will modify the document generation process to save the formatted IAP content to both a Markdown (`.md`) file and a plain text (`.txt`) file, in addition to displaying it in the console. This makes the generated IAP easily shareable and reviewable.

#### Instructions
1.  **Define `save_iap_to_files` function**: Create a new function that takes the `formatted_iap_document` string and a `filename_prefix`.
2.  **Save to Markdown**: Inside this function, write the `formatted_iap_document` to a file named `f'{filename_prefix}.md'`.
3.  **Save to Plain Text**: Convert the Markdown content to a plain text version and save it to `f'{filename_prefix}.txt'`. For simplicity, we will initially save the Markdown content directly to the text file.
4.  **Integrate**: Call the `save_iap_to_files` function after `generate_iap_document` in the main script, using a suitable filename prefix.

**Reasoning**:
Now, I will define the `save_iap_to_files` function and then update the main script to call this new function after generating the IAP document. This will create the `.md` and `.txt` files as requested, and also include all previously defined functions for completeness.



In [ ]:
import json
import datetime

def get_string_input(prompt, default=None):
    """Gets a string input from the user."""
    while True:
        value = input(prompt).strip()
        if value or default is not None:
            return value if value else default
        print("Input cannot be empty. Please provide a value.")

def get_datetime_input(prompt, format_str, value_type="date"):
    """Gets a date or time input from the user with validation."""
    while True:
        user_input = input(prompt).strip()
        if not user_input: # Allow empty input for optional fields
            return None
        try:
            if value_type == "date":
                return datetime.datetime.strptime(user_input, format_str).strftime('%Y-%m-%d')
            elif value_type == "time":
                return datetime.datetime.strptime(user_input, format_str).strftime('%H:%M')
            else:
                raise ValueError("Invalid value_type for get_datetime_input")
        except ValueError:
            print(f"Invalid format. Please use {format_str}.")

def get_list_of_dicts_input(prompt_singular, field_definitions):
    """Collects multiple entries, each a dictionary, for a list type field."""
    items = []
    print(f"\n--- Collecting {prompt_singular}s ---")
    while True:
        print(f"Enter details for a new {prompt_singular} (or type 'done' to finish):")
        temp_dict = {}

        # Check if user wants to stop before collecting any fields for the current item
        check_done = input(f"    (Type 'done' or press Enter to add a {prompt_singular}): ").strip().lower()
        if check_done == 'done':
            break

        all_fields_empty = True
        for field_name, field_type_info in field_definitions.items():
            field_type = field_type_info.get('type')
            field_prompt = field_type_info.get('prompt', f"    Enter {prompt_singular} {field_name}: ")
            field_format = field_type_info.get('format_str')
            field_default = field_type_info.get('default')

            if field_type == 'string':
                value = get_string_input(field_prompt, default=field_default)
            elif field_type == 'date':
                value = get_datetime_input(field_prompt, field_format, value_type='date')
            elif field_type == 'time':
                value = get_datetime_input(field_prompt, field_format, value_type='time')
            else: # Default to string for unknown types
                value = get_string_input(field_prompt, default=field_default)

            temp_dict[field_name] = value
            if value is not None and value != '': # Check if any field has a non-empty value
                all_fields_empty = False

        if temp_dict and not all_fields_empty: # Only add if at least some fields were filled
            items.append(temp_dict)

        # Offer to continue or stop
        if not get_string_input(f"Add another {prompt_singular}? (yes/no): ", default='yes').lower() == 'yes':
            break
    return items

def get_dict_input(prompt, field_definitions):
    """Collects fields for a dictionary type field."""
    print(f"\n--- Collecting {prompt} Details ---")
    data_dict = {}
    for field_name, field_type_info in field_definitions.items():
        field_type = field_type_info.get('type')
        field_prompt = field_type_info.get('prompt', f"    Enter {field_name}: ")
        field_format = field_type_info.get('format_str')
        field_default = field_type_info.get('default')

        if field_type == 'string':
            value = get_string_input(field_prompt, default=field_default)
        elif field_type == 'date':
            value = get_datetime_input(field_prompt, field_format, value_type='date')
        elif field_type == 'time':
            value = get_datetime_input(field_prompt, field_format, value_type='time')
        else:
            value = get_string_input(field_prompt, default=field_default)
        data_dict[field_name] = value
    return data_dict

# Existing IAP data model from previous steps
iap_data_model = {
    "Incident_Name": None,
    "Operational_Period": {
        "Start_Date": None,
        "End_Date": None,
        "Start_Time": None,
        "End_Time": None
    },
    "ICS_202_Incident_Objectives": {
        "Objectives": [],
        "General_Safety_Message": None,
        "Prepared_By": {
            "Name": None,
            "Position": None,
            "Signature": None
        },
        "Date": None,
        "Time": None
    },
    "ICS_203_Organization_Assignment_List": {
        "Incident_Commander": {
            "Name": None,
            "Agency": None,
            "Phone": None
        },
        "Section_Chiefs": {
            "Operations": {"Name": None, "Agency": None, "Phone": None},
            "Planning": {"Name": None, "Agency": None, "Phone": None},
            "Logistics": {"Name": None, "Agency": None, "Phone": None},
            "Finance_Admin": {"Name": None, "Agency": None, "Phone": None}
        },
        "Other_Positions": [] # List of dictionaries for other key positions
    },
    "ICS_204_Assignment_List": [
        # Each item in this list will be a dictionary representing one assignment
        {
            "Division_Group": None,
            "Branch": None,
            "Resources_Assigned": [], # List of dictionaries for resources (e.g., {'Name': 'Engine 1', 'Type': 'Fire Engine'})
            "Task_Activity": None,
            "Special_Instructions": None,
            "Reporting_Location": None,
            "Reporting_Time": None,
            "Supervisor": {"Name": None, "Contact": None}
        }
    ],
    "ICS_205_Incident_Radio_Communications_Plan": [
        # Each item in this list will be a dictionary representing one channel
        {
            "Channel_Name": None,
            "Function": None,
            "Assignment": None,
            "Frequency_Mode_Tone": None,
            "Remarks": None
        }
    ],
    "ICS_206_Medical_Plan": {
        "Medical_Aid_Stations": [],
        "Hospitals": [],
        "Ambulance_Services": [],
        "Medical_Emergency_Procedures": None
    },
    "Map_Diagram": {
        "Description": None,
        "File_Path": None # Placeholder for a file path or URL to a map/diagram
    },
    "Safety_Message_Plan": None # Could be a string or a more structured dictionary
}

def collect_iap_data(data_model):
    """Interactively collects Incident Action Plan data from the user."""
    iap_data = data_model.copy() # Create a mutable copy to populate

    print("\n--- Incident Action Plan Data Collection ---")

    # Incident Name
    iap_data["Incident_Name"] = get_string_input("Enter Incident Name: ")

    # Operational Period
    print("\n--- Operational Period ---")
    iap_data["Operational_Period"]["Start_Date"] = get_datetime_input("Enter Operational Period Start Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["Operational_Period"]["End_Date"] = get_datetime_input("Enter Operational Period End Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["Operational_Period"]["Start_Time"] = get_datetime_input("Enter Operational Period Start Time (HH:MM): ", "%H:%M", "time")
    iap_data["Operational_Period"]["End_Time"] = get_datetime_input("Enter Operational Period End Time (HH:MM): ", "%H:%M", "time")

    # ICS Form 202 - Incident Objectives
    print("\n--- ICS Form 202 - Incident Objectives ---")
    # Objectives - List of strings for simplicity, could be enhanced to list of dicts if more detail needed per obj
    iap_data["ICS_202_Incident_Objectives"]["Objectives"] = []
    print("Enter General Objectives (type 'done' to finish each objective):")
    while True:
        objective = get_string_input("    Objective: ")
        if objective.lower() == 'done':
            break
        if objective: # Only add if not empty
            iap_data["ICS_202_Incident_Objectives"]["Objectives"].append(objective)

    iap_data["ICS_202_Incident_Objectives"]["General_Safety_Message"] = get_string_input("Enter General Safety Message: ")

    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Name"] = get_string_input("Enter Preparer Name: ")
    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Position"] = get_string_input("Enter Preparer Position: ")
    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Signature"] = get_string_input("Enter Preparer Signature (or leave blank): ", default='')
    iap_data["ICS_202_Incident_Objectives"]["Date"] = get_datetime_input("Enter Prepared Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["ICS_202_Incident_Objectives"]["Time"] = get_datetime_input("Enter Prepared Time (HH:MM): ", "%H:%M", "time")

    # ICS Form 203 - Organization Assignment List
    print("\n--- ICS Form 203 - Organization Assignment List ---")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Name"] = get_string_input("Enter Incident Commander Name: ")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Agency"] = get_string_input("Enter Incident Commander Agency: ")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Phone"] = get_string_input("Enter Incident Commander Phone: ")

    for section, details in iap_data["ICS_203_Organization_Assignment_List"]["Section_Chiefs"].items():
        print(f"  --- {section} Section Chief ---")
        details["Name"] = get_string_input(f"    Enter {section} Section Chief Name: ")
        details["Agency"] = get_string_input(f"    Enter {section} Section Chief Agency: ")
        details["Phone"] = get_string_input(f"    Enter {section} Section Chief Phone: ")

    # Other Positions (list of dicts)
    iap_data["ICS_203_Organization_Assignment_List"]["Other_Positions"] = get_list_of_dicts_input(
        "Other Position",
        {
            "Name": {"type": "string", "prompt": "    Enter Name: "},
            "Position": {"type": "string", "prompt": "    Enter Position: "},
            "Agency": {"type": "string", "prompt": "    Enter Agency: "},
            "Phone": {"type": "string", "prompt": "    Enter Phone: "}
        }
    )

    # ICS Form 204 - Assignment List
    iap_data["ICS_204_Assignment_List"] = get_list_of_dicts_input(
        "Assignment",
        {
            "Division_Group": {"type": "string"},
            "Branch": {"type": "string", "prompt": "    Enter Branch (optional, press Enter to skip): ", "default": None},
            "Task_Activity": {"type": "string"},
            "Special_Instructions": {"type": "string", "prompt": "    Enter Special Instructions (optional, press Enter to skip): ", "default": None},
            "Reporting_Location": {"type": "string"},
            "Reporting_Time": {"type": "time", "format_str": "%H:%M"},
            "Supervisor_Name": {"type": "string", "prompt": "    Enter Supervisor Name: "},
            "Supervisor_Contact": {"type": "string", "prompt": "    Enter Supervisor Contact: "}
        }
    )
    # Special handling for Resources_Assigned within Assignment List
    for assignment in iap_data["ICS_204_Assignment_List"]:
        resources = []
        print(f"  --- Resources for {assignment.get('Division_Group', 'an assignment')} ---")
        while True:
            resource = get_string_input("    Enter Resource (e.g., Engine 1, Medic 5 - type 'done' to finish): ")
            if resource.lower() == 'done':
                break
            if resource:
                resources.append(resource)
        assignment["Resources_Assigned"] = resources
        # Flatting supervisor details
        assignment["Supervisor"] = {
            "Name": assignment.pop("Supervisor_Name"),
            "Contact": assignment.pop("Supervisor_Contact")
        }

    # ICS Form 205 - Incident Radio Communications Plan
    iap_data["ICS_205_Incident_Radio_Communications_Plan"] = get_list_of_dicts_input(
        "Radio Channel",
        {
            "Channel_Name": {"type": "string"},
            "Function": {"type": "string"},
            "Assignment": {"type": "string"},
            "Frequency_Mode_Tone": {"type": "string"},
            "Remarks": {"type": "string", "prompt": "    Enter Remarks (optional, press Enter to skip): ", "default": None}
        }
    )

    # ICS Form 206 - Medical Plan
    print("\n--- ICS Form 206 - Medical Plan ---")
    iap_data["ICS_206_Medical_Plan"]["Medical_Aid_Stations"] = get_list_of_dicts_input(
        "Medical Aid Station",
        {
            "Name": {"type": "string"},
            "Location": {"type": "string"},
            "Capabilities": {"type": "string"}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Hospitals"] = get_list_of_dicts_input(
        "Hospital",
        {
            "Name": {"type": "string"},
            "Location": {"type": "string"},
            "Contact": {"type": "string"},
            "Specializations": {"type": "string", "prompt": "    Enter Specializations (optional, press Enter to skip): ", "default": None}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Ambulance_Services"] = get_list_of_dicts_input(
        "Ambulance Service",
        {
            "Provider": {"type": "string"},
            "Contact": {"type": "string"},
            "Exchange_Points": {"type": "string", "prompt": "    Enter Exchange Points (optional, press Enter to skip): ", "default": None}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Medical_Emergency_Procedures"] = get_string_input("Enter Medical Emergency Procedures: ")

    # Map/Diagram
    print("\n--- Map / Diagram ---")
    iap_data["Map_Diagram"]["Description"] = get_string_input("Enter Map/Diagram Description (optional, press Enter to skip): ", default=None)
    iap_data["Map_Diagram"]["File_Path"] = get_string_input("Enter Map/Diagram File Path/URL (optional, press Enter to skip): ", default=None)

    # Safety Message/Plan
    iap_data["Safety_Message_Plan"] = get_string_input("Enter Safety Message/Plan details (optional, press Enter to skip): ", default=None)

    return iap_data

def generate_iap_document(iap_data):
    """Generates a formatted NIMS/ICS compliant Incident Action Plan document from collected data."""
    document_parts = []

    document_parts.append("# Incident Action Plan (IAP)\n")

    if iap_data.get("Incident_Name"):
        document_parts.append(f"## Incident Name: {iap_data['Incident_Name']}\n")

    # Operational Period
    op_period = iap_data.get("Operational_Period")
    if op_period and op_period.get("Start_Date"):
        document_parts.append("### 1. Operational Period\n")
        document_parts.append(f"* **Start:** {op_period.get('Start_Date')} {op_period.get('Start_Time')}\n")
        document_parts.append(f"* **End:** {op_period.get('End_Date')} {op_period.get('End_Time')}\n\n")

    # ICS 202 - Incident Objectives
    ics_202 = iap_data.get("ICS_202_Incident_Objectives")
    if ics_202 and (ics_202.get("Objectives") or ics_202.get("General_Safety_Message")):
        document_parts.append("### 2. ICS Form 202 - Incident Objectives\n")
        if ics_202.get("Objectives"):
            document_parts.append("#### Objectives:\n")
            for obj in ics_202["Objectives"]:
                document_parts.append(f"* {obj}\n")
        if ics_202.get("General_Safety_Message"):
            document_parts.append(f"#### General Safety Message:\n{ics_202['General_Safety_Message']}\n")
        if ics_202.get("Prepared_By") and ics_202["Prepared_By"].get("Name"):
            prep = ics_202["Prepared_By"]
            document_parts.append(f"* **Prepared By:** {prep.get('Name')} ({prep.get('Position')})\n")
            if prep.get('Signature'):
                document_parts.append(f"* **Signature:** {prep.get('Signature')}\n")
            document_parts.append(f"* **Date/Time:** {ics_202.get('Date')} {ics_202.get('Time')}\n\n")

    # ICS 203 - Organization Assignment List
    ics_203 = iap_data.get("ICS_203_Organization_Assignment_List")
    if ics_203 and (ics_203.get("Incident_Commander") or ics_203.get("Section_Chiefs") or ics_203.get("Other_Positions")):
        document_parts.append("### 3. ICS Form 203 - Organization Assignment List\n")
        if ics_203.get("Incident_Commander") and ics_203["Incident_Commander"].get("Name"):
            ic = ics_203["Incident_Commander"]
            document_parts.append(f"#### Incident Commander:\n")
            document_parts.append(f"* **Name:** {ic.get('Name')}\n")
            document_parts.append(f"* **Agency:** {ic.get('Agency')}\n")
            document_parts.append(f"* **Phone:** {ic.get('Phone')}\n\n")

        if ics_203.get("Section_Chiefs"):
            document_parts.append("#### Section Chiefs:\n")
            for section, details in ics_203["Section_Chiefs"].items():
                if details.get("Name"):
                    document_parts.append(f"* **{section.replace('_', ' ')}:** {details.get('Name')} ({details.get('Agency')}) - {details.get('Phone')}\n")
            document_parts.append("\n")

        if ics_203.get("Other_Positions"):
            document_parts.append("#### Other Key Positions:\n")
            for pos in ics_203["Other_Positions"]:
                if pos.get("Name"):
                    document_parts.append(f"* **{pos.get('Position')}:** {pos.get('Name')} ({pos.get('Agency')}) - {pos.get('Phone')}\n")
            document_parts.append("\n")

    # ICS 204 - Assignment List
    ics_204_list = iap_data.get("ICS_204_Assignment_List")
    if ics_204_list:
        document_parts.append("### 4. ICS Form 204 - Assignment List\n")
        for i, assignment in enumerate(ics_204_list):
            if assignment.get("Division_Group"):
                document_parts.append(f"#### Assignment {i+1}: {assignment.get('Division_Group')}\n")
                if assignment.get("Branch"):
                    document_parts.append(f"* **Branch:** {assignment.get('Branch')}\n")
                if assignment.get("Resources_Assigned"):
                    document_parts.append(f"* **Resources Assigned:** {', '.join(assignment['Resources_Assigned'])}\n")
                if assignment.get("Task_Activity"):
                    document_parts.append(f"* **Task/Activity:** {assignment.get('Task_Activity')}\n")
                if assignment.get("Special_Instructions"):
                    document_parts.append(f"* **Special Instructions:** {assignment.get('Special_Instructions')}\n")
                if assignment.get("Reporting_Location"):
                    document_parts.append(f"* **Reporting Location:** {assignment.get('Reporting_Location')}\n")
                if assignment.get("Reporting_Time"):
                    document_parts.append(f"* **Reporting Time:** {assignment.get('Reporting_Time')}\n")
                if assignment.get("Supervisor") and assignment["Supervisor"].get("Name"):
                    sup = assignment["Supervisor"]
                    document_parts.append(f"* **Supervisor:** {sup.get('Name')} ({sup.get('Contact')})\n")
                document_parts.append("\n")

    # ICS 205 - Incident Radio Communications Plan
    ics_205_list = iap_data.get("ICS_205_Incident_Radio_Communications_Plan")
    if ics_205_list:
        document_parts.append("### 5. ICS Form 205 - Incident Radio Communications Plan\n")
        for i, channel in enumerate(ics_205_list):
            if channel.get("Channel_Name"):
                document_parts.append(f"#### Channel {i+1}: {channel.get('Channel_Name')}\n")
                document_parts.append(f"* **Function:** {channel.get('Function')}\n")
                document_parts.append(f"* **Assignment:** {channel.get('Assignment')}\n")
                document_parts.append(f"* **Frequency/Mode/Tone:** {channel.get('Frequency_Mode_Tone')}\n")
                if channel.get("Remarks"):
                    document_parts.append(f"* **Remarks:** {channel.get('Remarks')}\n")
                document_parts.append("\n")

    # ICS 206 - Medical Plan
    ics_206 = iap_data.get("ICS_206_Medical_Plan")
    if ics_206 and (ics_206.get("Medical_Aid_Stations") or ics_206.get("Hospitals") or ics_206.get("Ambulance_Services") or ics_206.get("Medical_Emergency_Procedures")):
        document_parts.append("### 6. ICS Form 206 - Medical Plan\n")
        if ics_206.get("Medical_Aid_Stations"):
            document_parts.append("#### Medical Aid Stations:\n")
            for station in ics_206["Medical_Aid_Stations"]:
                if station.get("Name"):
                    document_parts.append(f"* **{station.get('Name')}:** {station.get('Location')} (Capabilities: {station.get('Capabilities')})\n")
            document_parts.append("\n")

        if ics_206.get("Hospitals"):
            document_parts.append("#### Hospitals:\n")
            for hospital in ics_206["Hospitals"]:
                if hospital.get("Name"):
                    specs = f" (Specializations: {hospital['Specializations']})" if hospital.get('Specializations') else ''
                    document_parts.append(f"* **{hospital.get('Name')}:** {hospital.get('Location')} (Contact: {hospital.get('Contact')}){specs}\n")
            document_parts.append("\n")

        if ics_206.get("Ambulance_Services"):
            document_parts.append("#### Ambulance Services:\n")
            for service in ics_206["Ambulance_Services"]:
                if service.get("Provider"):
                    ex_points = f" (Exchange Points: {service['Exchange_Points']})" if service.get('Exchange_Points') else ''
                    document_parts.append(f"* **{service.get('Provider')}:** Contact: {service.get('Contact')}{ex_points}\n")
            document_parts.append("\n")

        if ics_206.get("Medical_Emergency_Procedures"):
            document_parts.append(f"#### Medical Emergency Procedures:\n{ics_206['Medical_Emergency_Procedures']}\n\n")

    # Map/Diagram
    map_diag = iap_data.get("Map_Diagram")
    if map_diag and (map_diag.get("Description") or map_diag.get("File_Path")):
        document_parts.append("### 7. Map / Diagram\n")
        if map_diag.get("Description"):
            document_parts.append(f"* **Description:** {map_diag.get('Description')}\n")
        if map_diag.get("File_Path"):
            document_parts.append(f"* **File Path/URL:** {map_diag.get('File_Path')}\n")
        document_parts.append("\n")

    # Safety Message/Plan
    if iap_data.get("Safety_Message_Plan"):
        document_parts.append("### 8. Safety Message / Plan\n")
        document_parts.append(f"{iap_data['Safety_Message_Plan']}\n\n")

    return "".join(document_parts)

def save_iap_to_files(formatted_iap_document, filename_prefix="incident_iap"):
    """Saves the formatted IAP document to Markdown and plain text files."""
    markdown_filename = f"{filename_prefix}.md"
    text_filename = f"{filename_prefix}.txt"

    try:
        with open(markdown_filename, "w", encoding="utf-8") as f:
            f.write(formatted_iap_document)
        print(f"IAP successfully saved to {markdown_filename}")

        # For simplicity, saving the Markdown content directly to the text file
        # A more robust solution might involve stripping markdown or converting to pure text.
        with open(text_filename, "w", encoding="utf-8") as f:
            f.write(formatted_iap_document)
        print(f"IAP successfully saved to {text_filename}")

    except IOError as e:
        print(f"Error saving files: {e}")


# --- Main Execution Flow ---
print("Starting interactive IAP data collection. Follow the prompts.")
filled_iap_data = collect_iap_data(iap_data_model)

print("\n--- Collected IAP Data ---")
print(json.dumps(filled_iap_data, indent=4))

print("\n--- Generating IAP Document ---")
formatted_iap_document = generate_iap_document(filled_iap_data)
print(formatted_iap_document)

# Save the generated document to files
save_iap_to_files(formatted_iap_document, filename_prefix="generated_iap")


## Implement PDF Export

### Subtask:
Integrate functionality to convert the generated IAP document into a Portable Document Format (PDF) file for official use. This will likely involve using a Python library for PDF generation (e.g., ReportLab or FPDF) or a Markdown-to-PDF conversion tool.


**Reasoning**:
The user wants to implement PDF export functionality. First, I need to provide the installation instructions for the required libraries, 'WeasyPrint' and 'markdown', in a separate code cell.



In [ ]:
pip install WeasyPrint markdown

**Reasoning**:
Now that the necessary libraries are installed, I will define the `save_iap_to_pdf` function as instructed. This function will convert the Markdown content to HTML and then use WeasyPrint to generate a PDF file.



In [ ]:
import markdown
from weasyprint import HTML
import os

def save_iap_to_pdf(formatted_iap_document, filename_prefix="incident_iap"):
    """Converts the Markdown formatted IAP document to HTML and then saves it as a PDF file."""
    pdf_filename = f"{filename_prefix}.pdf"

    try:
        # Convert Markdown to HTML
        html_content = markdown.markdown(formatted_iap_document)

        # Add some basic styling for better PDF output
        html_styled = f"""
<html>
<head>
    <meta charset="utf-8">
    <title>{filename_prefix.replace('_', ' ').title()} IAP</title>
    <style>
        body {{ font-family: sans-serif; margin: 1in; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 0.5em; }}
        h2 {{ color: #34495e; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }}
        h3 {{ color: #34495e; margin-top: 1.5em; }}
        h4 {{ color: #34495e; margin-top: 1em; }}
        ul {{ list-style-type: disc; margin-left: 1.5em; }}
        li {{ margin-bottom: 0.5em; }}
        b {{ font-weight: bold; }}
    </style>
</head>
<body>
{html_content}
</body>
</html>
"""

        # Generate PDF from HTML
        HTML(string=html_styled).write_pdf(pdf_filename)
        print(f"IAP successfully saved to {pdf_filename}")

    except Exception as e:
        print(f"Error saving PDF file: {e}")

print("PDF export function 'save_iap_to_pdf' defined.")

**Reasoning**:
Now that the `save_iap_to_pdf` function is defined, I will integrate it into the main execution flow to generate a PDF document alongside the Markdown and text files.



In [ ]:
import json
import datetime
import markdown
from weasyprint import HTML
import os

def get_string_input(prompt, default=None):
    """Gets a string input from the user."""
    while True:
        value = input(prompt).strip()
        if value or default is not None:
            return value if value else default
        print("Input cannot be empty. Please provide a value.")

def get_datetime_input(prompt, format_str, value_type="date"):
    """Gets a date or time input from the user with validation."""
    while True:
        user_input = input(prompt).strip()
        if not user_input: # Allow empty input for optional fields
            return None
        try:
            if value_type == "date":
                return datetime.datetime.strptime(user_input, format_str).strftime('%Y-%m-%d')
            elif value_type == "time":
                return datetime.datetime.strptime(user_input, format_str).strftime('%H:%M')
            else:
                raise ValueError("Invalid value_type for get_datetime_input")
        except ValueError:
            print(f"Invalid format. Please use {format_str}.")

def get_list_of_dicts_input(prompt_singular, field_definitions):
    """Collects multiple entries, each a dictionary, for a list type field."""
    items = []
    print(f"\n--- Collecting {prompt_singular}s ---")
    while True:
        print(f"Enter details for a new {prompt_singular} (or type 'done' to finish):")
        temp_dict = {}

        # Check if user wants to stop before collecting any fields for the current item
        check_done = input(f"    (Type 'done' or press Enter to add a {prompt_singular}): ").strip().lower()
        if check_done == 'done':
            break

        all_fields_empty = True
        for field_name, field_type_info in field_definitions.items():
            field_type = field_type_info.get('type')
            field_prompt = field_type_info.get('prompt', f"    Enter {prompt_singular} {field_name}: ")
            field_format = field_type_info.get('format_str')
            field_default = field_type_info.get('default')

            if field_type == 'string':
                value = get_string_input(field_prompt, default=field_default)
            elif field_type == 'date':
                value = get_datetime_input(field_prompt, field_format, value_type='date')
            elif field_type == 'time':
                value = get_datetime_input(field_prompt, field_format, value_type='time')
            else: # Default to string for unknown types
                value = get_string_input(field_prompt, default=field_default)

            temp_dict[field_name] = value
            if value is not None and value != '': # Check if any field has a non-empty value
                all_fields_empty = False

        if temp_dict and not all_fields_empty: # Only add if at least some fields were filled
            items.append(temp_dict)

        # Offer to continue or stop
        if not get_string_input(f"Add another {prompt_singular}? (yes/no): ", default='yes').lower() == 'yes':
            break
    return items

def get_dict_input(prompt, field_definitions):
    """Collects fields for a dictionary type field."""
    print(f"\n--- Collecting {prompt} Details ---")
    data_dict = {}
    for field_name, field_type_info in field_definitions.items():
        field_type = field_type_info.get('type')
        field_prompt = field_type_info.get('prompt', f"    Enter {field_name}: ")
        field_format = field_type_info.get('format_str')
        field_default = field_type_info.get('default')

        if field_type == 'string':
            value = get_string_input(field_prompt, default=field_default)
        elif field_type == 'date':
            value = get_datetime_input(field_prompt, field_format, value_type='date')
        elif field_type == 'time':
            value = get_datetime_input(field_prompt, field_format, value_type='time')
        else:
            value = get_string_input(field_prompt, default=field_default)
        data_dict[field_name] = value
    return data_dict

# Existing IAP data model from previous steps
iap_data_model = {
    "Incident_Name": None,
    "Operational_Period": {
        "Start_Date": None,
        "End_Date": None,
        "Start_Time": None,
        "End_Time": None
    },
    "ICS_202_Incident_Objectives": {
        "Objectives": [],
        "General_Safety_Message": None,
        "Prepared_By": {
            "Name": None,
            "Position": None,
            "Signature": None
        },
        "Date": None,
        "Time": None
    },
    "ICS_203_Organization_Assignment_List": {
        "Incident_Commander": {
            "Name": None,
            "Agency": None,
            "Phone": None
        },
        "Section_Chiefs": {
            "Operations": {"Name": None, "Agency": None, "Phone": None},
            "Planning": {"Name": None, "Agency": None, "Phone": None},
            "Logistics": {"Name": None, "Agency": None, "Phone": None},
            "Finance_Admin": {"Name": None, "Agency": None, "Phone": None}
        },
        "Other_Positions": [] # List of dictionaries for other key positions
    },
    "ICS_204_Assignment_List": [
        # Each item in this list will be a dictionary representing one assignment
        {
            "Division_Group": None,
            "Branch": None,
            "Resources_Assigned": [], # List of dictionaries for resources (e.g., {'Name': 'Engine 1', 'Type': 'Fire Engine'})
            "Task_Activity": None,
            "Special_Instructions": None,
            "Reporting_Location": None,
            "Reporting_Time": None,
            "Supervisor": {"Name": None, "Contact": None}
        }
    ],
    "ICS_205_Incident_Radio_Communications_Plan": [
        # Each item in this list will be a dictionary representing one channel
        {
            "Channel_Name": None,
            "Function": None,
            "Assignment": None,
            "Frequency_Mode_Tone": None,
            "Remarks": None
        }
    ],
    "ICS_206_Medical_Plan": {
        "Medical_Aid_Stations": [],
        "Hospitals": [],
        "Ambulance_Services": [],
        "Medical_Emergency_Procedures": None
    },
    "Map_Diagram": {
        "Description": None,
        "File_Path": None # Placeholder for a file path or URL to a map/diagram
    },
    "Safety_Message_Plan": None # Could be a string or a more structured dictionary
}

def collect_iap_data(data_model):
    """Interactively collects Incident Action Plan data from the user."""
    iap_data = data_model.copy() # Create a mutable copy to populate

    print("\n--- Incident Action Plan Data Collection ---")

    # Incident Name
    iap_data["Incident_Name"] = get_string_input("Enter Incident Name: ")

    # Operational Period
    print("\n--- Operational Period ---")
    iap_data["Operational_Period"]["Start_Date"] = get_datetime_input("Enter Operational Period Start Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["Operational_Period"]["End_Date"] = get_datetime_input("Enter Operational Period End Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["Operational_Period"]["Start_Time"] = get_datetime_input("Enter Operational Period Start Time (HH:MM): ", "%H:%M", "time")
    iap_data["Operational_Period"]["End_Time"] = get_datetime_input("Enter Operational Period End Time (HH:MM): ", "%H:%M", "time")

    # ICS Form 202 - Incident Objectives
    print("\n--- ICS Form 202 - Incident Objectives ---")
    # Objectives - List of strings for simplicity, could be enhanced to list of dicts if more detail needed per obj
    iap_data["ICS_202_Incident_Objectives"]["Objectives"] = []
    print("Enter General Objectives (type 'done' to finish each objective):")
    while True:
        objective = get_string_input("    Objective: ")
        if objective.lower() == 'done':
            break
        if objective: # Only add if not empty
            iap_data["ICS_202_Incident_Objectives"]["Objectives"].append(objective)

    iap_data["ICS_202_Incident_Objectives"]["General_Safety_Message"] = get_string_input("Enter General Safety Message: ")

    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Name"] = get_string_input("Enter Preparer Name: ")
    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Position"] = get_string_input("Enter Preparer Position: ")
    iap_data["ICS_202_Incident_Objectives"]["Prepared_By"]["Signature"] = get_string_input("Enter Preparer Signature (or leave blank): ", default='')
    iap_data["ICS_202_Incident_Objectives"]["Date"] = get_datetime_input("Enter Prepared Date (YYYY-MM-DD): ", "%Y-%m-%d", "date")
    iap_data["ICS_202_Incident_Objectives"]["Time"] = get_datetime_input("Enter Prepared Time (HH:MM): ", "%H:%M", "time")

    # ICS Form 203 - Organization Assignment List
    print("\n--- ICS Form 203 - Organization Assignment List ---")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Name"] = get_string_input("Enter Incident Commander Name: ")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Agency"] = get_string_input("Enter Incident Commander Agency: ")
    iap_data["ICS_203_Organization_Assignment_List"]["Incident_Commander"]["Phone"] = get_string_input("Enter Incident Commander Phone: ")

    for section, details in iap_data["ICS_203_Organization_Assignment_List"]["Section_Chiefs"].items():
        print(f"  --- {section} Section Chief ---")
        details["Name"] = get_string_input(f"    Enter {section} Section Chief Name: ")
        details["Agency"] = get_string_input(f"    Enter {section} Section Chief Agency: ")
        details["Phone"] = get_string_input(f"    Enter {section} Section Chief Phone: ")

    # Other Positions (list of dicts)
    iap_data["ICS_203_Organization_Assignment_List"]["Other_Positions"] = get_list_of_dicts_input(
        "Other Position",
        {
            "Name": {"type": "string", "prompt": "    Enter Name: "},
            "Position": {"type": "string", "prompt": "    Enter Position: "},
            "Agency": {"type": "string", "prompt": "    Enter Agency: "},
            "Phone": {"type": "string", "prompt": "    Enter Phone: "}
        }
    )

    # ICS Form 204 - Assignment List
    iap_data["ICS_204_Assignment_List"] = get_list_of_dicts_input(
        "Assignment",
        {
            "Division_Group": {"type": "string"},
            "Branch": {"type": "string", "prompt": "    Enter Branch (optional, press Enter to skip): ", "default": None},
            "Task_Activity": {"type": "string"},
            "Special_Instructions": {"type": "string", "prompt": "    Enter Special Instructions (optional, press Enter to skip): ", "default": None},
            "Reporting_Location": {"type": "string"},
            "Reporting_Time": {"type": "time", "format_str": "%H:%M"},
            "Supervisor_Name": {"type": "string", "prompt": "    Enter Supervisor Name: "},
            "Supervisor_Contact": {"type": "string", "prompt": "    Enter Supervisor Contact: "}
        }
    )
    # Special handling for Resources_Assigned within Assignment List
    for assignment in iap_data["ICS_204_Assignment_List"]:
        resources = []
        print(f"  --- Resources for {assignment.get('Division_Group', 'an assignment')} ---")
        while True:
            resource = get_string_input("    Enter Resource (e.g., Engine 1, Medic 5 - type 'done' to finish): ")
            if resource.lower() == 'done':
                break
            if resource:
                resources.append(resource)
        assignment["Resources_Assigned"] = resources
        # Flatting supervisor details
        assignment["Supervisor"] = {
            "Name": assignment.pop("Supervisor_Name"),
            "Contact": assignment.pop("Supervisor_Contact")
        }

    # ICS Form 205 - Incident Radio Communications Plan
    iap_data["ICS_205_Incident_Radio_Communications_Plan"] = get_list_of_dicts_input(
        "Radio Channel",
        {
            "Channel_Name": {"type": "string"},
            "Function": {"type": "string"},
            "Assignment": {"type": "string"},
            "Frequency_Mode_Tone": {"type": "string"},
            "Remarks": {"type": "string", "prompt": "    Enter Remarks (optional, press Enter to skip): ", "default": None}
        }
    )

    # ICS Form 206 - Medical Plan
    print("\n--- ICS Form 206 - Medical Plan ---")
    iap_data["ICS_206_Medical_Plan"]["Medical_Aid_Stations"] = get_list_of_dicts_input(
        "Medical Aid Station",
        {
            "Name": {"type": "string"},
            "Location": {"type": "string"},
            "Capabilities": {"type": "string"}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Hospitals"] = get_list_of_dicts_input(
        "Hospital",
        {
            "Name": {"type": "string"},
            "Location": {"type": "string"},
            "Contact": {"type": "string"},
            "Specializations": {"type": "string", "prompt": "    Enter Specializations (optional, press Enter to skip): ", "default": None}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Ambulance_Services"] = get_list_of_dicts_input(
        "Ambulance Service",
        {
            "Provider": {"type": "string"},
            "Contact": {"type": "string"},
            "Exchange_Points": {"type": "string", "prompt": "    Enter Exchange Points (optional, press Enter to skip): ", "default": None}
        }
    )
    iap_data["ICS_206_Medical_Plan"]["Medical_Emergency_Procedures"] = get_string_input("Enter Medical Emergency Procedures: ")

    # Map/Diagram
    print("\n--- Map / Diagram ---")
    iap_data["Map_Diagram"]["Description"] = get_string_input("Enter Map/Diagram Description (optional, press Enter to skip): ", default=None)
    iap_data["Map_Diagram"]["File_Path"] = get_string_input("Enter Map/Diagram File Path/URL (optional, press Enter to skip): ", default=None)

    # Safety Message/Plan
    iap_data["Safety_Message_Plan"] = get_string_input("Enter Safety Message/Plan details (optional, press Enter to skip): ", default=None)

    return iap_data

def generate_iap_document(iap_data):
    """Generates a formatted NIMS/ICS compliant Incident Action Plan document from collected data."""
    document_parts = []

    document_parts.append("# Incident Action Plan (IAP)\n")

    if iap_data.get("Incident_Name"):
        document_parts.append(f"## Incident Name: {iap_data['Incident_Name']}\n")

    # Operational Period
    op_period = iap_data.get("Operational_Period")
    if op_period and op_period.get("Start_Date"):
        document_parts.append("### 1. Operational Period\n")
        document_parts.append(f"* **Start:** {op_period.get('Start_Date')} {op_period.get('Start_Time')}\n")
        document_parts.append(f"* **End:** {op_period.get('End_Date')} {op_period.get('End_Time')}\n\n")

    # ICS 202 - Incident Objectives
    ics_202 = iap_data.get("ICS_202_Incident_Objectives")
    if ics_202 and (ics_202.get("Objectives") or ics_202.get("General_Safety_Message")):
        document_parts.append("### 2. ICS Form 202 - Incident Objectives\n")
        if ics_202.get("Objectives"):
            document_parts.append("#### Objectives:\n")
            for obj in ics_202["Objectives"]:
                document_parts.append(f"* {obj}\n")
        if ics_202.get("General_Safety_Message"):
            document_parts.append(f"#### General Safety Message:\n{ics_202['General_Safety_Message']}\n")
        if ics_202.get("Prepared_By") and ics_202["Prepared_By"].get("Name"):
            prep = ics_202["Prepared_By"]
            document_parts.append(f"* **Prepared By:** {prep.get('Name')} ({prep.get('Position')})\n")
            if prep.get('Signature'):
                document_parts.append(f"* **Signature:** {prep.get('Signature')}\n")
            document_parts.append(f"* **Date/Time:** {ics_202.get('Date')} {ics_202.get('Time')}\n\n")

    # ICS 203 - Organization Assignment List
    ics_203 = iap_data.get("ICS_203_Organization_Assignment_List")
    if ics_203 and (ics_203.get("Incident_Commander") or ics_203.get("Section_Chiefs") or ics_203.get("Other_Positions")):
        document_parts.append("### 3. ICS Form 203 - Organization Assignment List\n")
        if ics_203.get("Incident_Commander") and ics_203["Incident_Commander"].get("Name"):
            ic = ics_203["Incident_Commander"]
            document_parts.append(f"#### Incident Commander:\n")
            document_parts.append(f"* **Name:** {ic.get('Name')}\n")
            document_parts.append(f"* **Agency:** {ic.get('Agency')}\n")
            document_parts.append(f"* **Phone:** {ic.get('Phone')}\n\n")

        if ics_203.get("Section_Chiefs"):
            document_parts.append("#### Section Chiefs:\n")
            for section, details in ics_203["Section_Chiefs"].items():
                if details.get("Name"):
                    document_parts.append(f"* **{section.replace('_', ' ')}:** {details.get('Name')} ({details.get('Agency')}) - {details.get('Phone')}\n")
            document_parts.append("\n")

        if ics_203.get("Other_Positions"):
            document_parts.append("#### Other Key Positions:\n")
            for pos in ics_203["Other_Positions"]:
                if pos.get("Name"):
                    document_parts.append(f"* **{pos.get('Position')}:** {pos.get('Name')} ({pos.get('Agency')}) - {pos.get('Phone')}\n")
            document_parts.append("\n")

    # ICS 204 - Assignment List
    ics_204_list = iap_data.get("ICS_204_Assignment_List")
    if ics_204_list:
        document_parts.append("### 4. ICS Form 204 - Assignment List\n")
        for i, assignment in enumerate(ics_204_list):
            if assignment.get("Division_Group"):
                document_parts.append(f"#### Assignment {i+1}: {assignment.get('Division_Group')}\n")
                if assignment.get("Branch"):
                    document_parts.append(f"* **Branch:** {assignment.get('Branch')}\n")
                if assignment.get("Resources_Assigned"):
                    document_parts.append(f"* **Resources Assigned:** {', '.join(assignment['Resources_Assigned'])}\n")
                if assignment.get("Task_Activity"):
                    document_parts.append(f"* **Task/Activity:** {assignment.get('Task_Activity')}\n")
                if assignment.get("Special_Instructions"):
                    document_parts.append(f"* **Special Instructions:** {assignment.get('Special_Instructions')}\n")
                if assignment.get("Reporting_Location"):
                    document_parts.append(f"* **Reporting Location:** {assignment.get('Reporting_Location')}\n")
                if assignment.get("Reporting_Time"):
                    document_parts.append(f"* **Reporting Time:** {assignment.get('Reporting_Time')}\n")
                if assignment.get("Supervisor") and assignment["Supervisor"].get("Name"):
                    sup = assignment["Supervisor"]
                    document_parts.append(f"* **Supervisor:** {sup.get('Name')} ({sup.get('Contact')})\n")
                document_parts.append("\n")

    # ICS 205 - Incident Radio Communications Plan
    ics_205_list = iap_data.get("ICS_205_Incident_Radio_Communications_Plan")
    if ics_205_list:
        document_parts.append("### 5. ICS Form 205 - Incident Radio Communications Plan\n")
        for i, channel in enumerate(ics_205_list):
            if channel.get("Channel_Name"):
                document_parts.append(f"#### Channel {i+1}: {channel.get('Channel_Name')}\n")
                document_parts.append(f"* **Function:** {channel.get('Function')}\n")
                document_parts.append(f"* **Assignment:** {channel.get('Assignment')}\n")
                document_parts.append(f"* **Frequency/Mode/Tone:** {channel.get('Frequency_Mode_Tone')}\n")
                if channel.get("Remarks"):
                    document_parts.append(f"* **Remarks:** {channel.get('Remarks')}\n")
                document_parts.append("\n")

    # ICS 206 - Medical Plan
    ics_206 = iap_data.get("ICS_206_Medical_Plan")
    if ics_206 and (ics_206.get("Medical_Aid_Stations") or ics_206.get("Hospitals") or ics_206.get("Ambulance_Services") or ics_206.get("Medical_Emergency_Procedures")):
        document_parts.append("### 6. ICS Form 206 - Medical Plan\n")
        if ics_206.get("Medical_Aid_Stations"):
            document_parts.append("#### Medical Aid Stations:\n")
            for station in ics_206["Medical_Aid_Stations"]:
                if station.get("Name"):
                    document_parts.append(f"* **{station.get('Name')}:** {station.get('Location')} (Capabilities: {station.get('Capabilities')})\n")
            document_parts.append("\n")

        if ics_206.get("Hospitals"):
            document_parts.append("#### Hospitals:\n")
            for hospital in ics_206["Hospitals"]:
                if hospital.get("Name"):
                    specs = f" (Specializations: {hospital['Specializations']})" if hospital.get('Specializations') else ''
                    document_parts.append(f"* **{hospital.get('Name')}:** {hospital.get('Location')} (Contact: {hospital.get('Contact')}){specs}\n")
            document_parts.append("\n")

        if ics_206.get("Ambulance_Services"):
            document_parts.append("#### Ambulance Services:\n")
            for service in ics_206["Ambulance_Services"]:
                if service.get("Provider"):
                    ex_points = f" (Exchange Points: {service['Exchange_Points']})" if service.get('Exchange_Points') else ''
                    document_parts.append(f"* **{service.get('Provider')}:** Contact: {service.get('Contact')}{ex_points}\n")
            document_parts.append("\n")

        if ics_206.get("Medical_Emergency_Procedures"):
            document_parts.append(f"#### Medical Emergency Procedures:\n{ics_206['Medical_Emergency_Procedures']}\n\n")

    # Map/Diagram
    map_diag = iap_data.get("Map_Diagram")
    if map_diag and (map_diag.get("Description") or map_diag.get("File_Path")):
        document_parts.append("### 7. Map / Diagram\n")
        if map_diag.get("Description"):
            document_parts.append(f"* **Description:** {map_diag.get('Description')}\n")
        if map_diag.get("File_Path"):
            document_parts.append(f"* **File Path/URL:** {map_diag.get('File_Path')}\n")
        document_parts.append("\n")

    # Safety Message/Plan
    if iap_data.get("Safety_Message_Plan"):
        document_parts.append("### 8. Safety Message / Plan\n")
        document_parts.append(f"{iap_data['Safety_Message_Plan']}\n\n")

    return "".join(document_parts)

def save_iap_to_files(formatted_iap_document, filename_prefix="incident_iap"):
    """Saves the formatted IAP document to Markdown and plain text files."""
    markdown_filename = f"{filename_prefix}.md"
    text_filename = f"{filename_prefix}.txt"

    try:
        with open(markdown_filename, "w", encoding="utf-8") as f:
            f.write(formatted_iap_document)
        print(f"IAP successfully saved to {markdown_filename}")

        # For simplicity, saving the Markdown content directly to the text file
        # A more robust solution might involve stripping markdown or converting to pure text.
        with open(text_filename, "w", encoding="utf-8") as f:
            f.write(formatted_iap_document)
        print(f"IAP successfully saved to {text_filename}")

    except IOError as e:
        print(f"Error saving files: {e}")

def save_iap_to_pdf(formatted_iap_document, filename_prefix="incident_iap"):
    """Converts the Markdown formatted IAP document to HTML and then saves it as a PDF file."""
    pdf_filename = f"{filename_prefix}.pdf"

    try:
        # Convert Markdown to HTML
        html_content = markdown.markdown(formatted_iap_document)

        # Add some basic styling for better PDF output
        html_styled = f"""
<html>
<head>
    <meta charset=\"utf-8\">
    <title>{filename_prefix.replace('_', ' ').title()} IAP</title>
    <style>
        body {{ font-family: sans-serif; margin: 1in; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 0.5em; }}
        h2 {{ color: #34495e; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }}
        h3 {{ color: #34495e; margin-top: 1.5em; }}
        h4 {{ color: #34495e; margin-top: 1em; }}
        ul {{ list-style-type: disc; margin-left: 1.5em; }}
        li {{ margin-bottom: 0.5em; }}
        b {{ font-weight: bold; }}
    </style>
</head>
<body>
{html_content}
</body>
</html>
"""

        # Generate PDF from HTML
        HTML(string=html_styled).write_pdf(pdf_filename)
        print(f"IAP successfully saved to {pdf_filename}")

    except Exception as e:
        print(f"Error saving PDF file: {e}")


# --- Main Execution Flow ---
print("Starting interactive IAP data collection. Follow the prompts.")
filled_iap_data = collect_iap_data(iap_data_model)

print("\n--- Collected IAP Data ---")
print(json.dumps(filled_iap_data, indent=4))

print("\n--- Generating IAP Document ---")
formatted_iap_document = generate_iap_document(filled_iap_data)
print(formatted_iap_document)

# Save the generated document to files
save_iap_to_files(formatted_iap_document, filename_prefix="generated_iap")
save_iap_to_pdf(formatted_iap_document, filename_prefix="generated_iap")

**Reasoning**:
The subtask is to develop the foundational GUI structure using Tkinter, including input fields, buttons, and output format selection. I have created a Python script that imports `tkinter`, sets up the main window, adds placeholder widgets for essential IAP information, includes action buttons, and provides checkboxes for output format selection, arranging them with a layout manager. This directly addresses all instructions in the subtask.



In [ ]:
import tkinter as tk
from tkinter import ttk

def create_iap_gui():
    # 1. Create the main application window
    root = tk.Tk()

    # 2. Set the title of the GUI window
    root.title("NIMS/ICS IAP Generator")

    # Create a main frame for padding and organization
    main_frame = ttk.Frame(root, padding="10 10 10 10")
    main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
    root.columnconfigure(0, weight=1)
    root.rowconfigure(0, weight=1)

    # 3. Basic structure for Incident Details
    incident_frame = ttk.LabelFrame(main_frame, text="Incident Details", padding="10 10 10 10")
    incident_frame.grid(row=0, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
    incident_frame.columnconfigure(1, weight=1)

    ttk.Label(incident_frame, text="Incident Name:").grid(row=0, column=0, sticky=tk.W, pady=2, padx=5)
    incident_name_entry = ttk.Entry(incident_frame, width=50)
    incident_name_entry.grid(row=0, column=1, sticky=(tk.W, tk.E), pady=2, padx=5)

    # 4. Basic structure for Operational Period
    op_period_frame = ttk.LabelFrame(main_frame, text="Operational Period", padding="10 10 10 10")
    op_period_frame.grid(row=1, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
    op_period_frame.columnconfigure(1, weight=1)
    op_period_frame.columnconfigure(3, weight=1)

    ttk.Label(op_period_frame, text="Start Date (YYYY-MM-DD):").grid(row=0, column=0, sticky=tk.W, pady=2, padx=5)
    op_start_date_entry = ttk.Entry(op_period_frame, width=20)
    op_start_date_entry.grid(row=0, column=1, sticky=(tk.W, tk.E), pady=2, padx=5)

    ttk.Label(op_period_frame, text="End Date (YYYY-MM-DD):").grid(row=0, column=2, sticky=tk.W, pady=2, padx=5)
    op_end_date_entry = ttk.Entry(op_period_frame, width=20)
    op_end_date_entry.grid(row=0, column=3, sticky=(tk.W, tk.E), pady=2, padx=5)

    ttk.Label(op_period_frame, text="Start Time (HH:MM):").grid(row=1, column=0, sticky=tk.W, pady=2, padx=5)
    op_start_time_entry = ttk.Entry(op_period_frame, width=20)
    op_start_time_entry.grid(row=1, column=1, sticky=(tk.W, tk.E), pady=2, padx=5)

    ttk.Label(op_period_frame, text="End Time (HH:MM):").grid(row=1, column=2, sticky=tk.W, pady=2, padx=5)
    op_end_time_entry = ttk.Entry(op_period_frame, width=20)
    op_end_time_entry.grid(row=1, column=3, sticky=(tk.W, tk.E), pady=2, padx=5)

    # Placeholder for other IAP sections (e.g., Objectives, Organization)
    placeholder_frame = ttk.LabelFrame(main_frame, text="Other IAP Sections (Placeholders)", padding="10 10 10 10")
    placeholder_frame.grid(row=2, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
    ttk.Label(placeholder_frame, text="More input fields would go here for ICS 202, 203, 204, etc.").grid(row=0, column=0, sticky=tk.W, padx=5, pady=5)

    # 5. Buttons for actions
    button_frame = ttk.Frame(main_frame, padding="5 0 5 0")
    button_frame.grid(row=3, column=0, sticky=(tk.W, tk.E), pady=10)
    button_frame.columnconfigure(0, weight=1)
    button_frame.columnconfigure(1, weight=1)
    button_frame.columnconfigure(2, weight=1)

    generate_button = ttk.Button(button_frame, text="Generate IAP", command=lambda: print("Generate IAP clicked"))
    generate_button.grid(row=0, column=0, padx=5)

    save_button = ttk.Button(button_frame, text="Save IAP", command=lambda: print("Save IAP clicked"))
    save_button.grid(row=0, column=1, padx=5)

    exit_button = ttk.Button(button_frame, text="Exit", command=root.destroy)
    exit_button.grid(row=0, column=2, padx=5)

    # 6. Options for output format selection
    output_format_frame = ttk.LabelFrame(main_frame, text="Output Formats", padding="10 10 10 10")
    output_format_frame.grid(row=3, column=1, sticky=(tk.E), pady=10, padx=5)

    # Variables to hold checkbox states
    md_var = tk.BooleanVar(value=True)
    txt_var = tk.BooleanVar(value=True)
    pdf_var = tk.BooleanVar(value=True)

    ttk.Checkbutton(output_format_frame, text="Markdown (.md)", variable=md_var).grid(row=0, column=0, sticky=tk.W, padx=2)
    ttk.Checkbutton(output_format_frame, text="Plain Text (.txt)", variable=txt_var).grid(row=1, column=0, sticky=tk.W, padx=2)
    ttk.Checkbutton(output_format_frame, text="PDF (.pdf)", variable=pdf_var).grid(row=2, column=0, sticky=tk.W, padx=2)

    # 7. Start the Tkinter event loop
    root.mainloop()

print("Executing GUI creation function.")
create_iap_gui()
print("Basic GUI window displayed. Close the window to continue.")


# Task
Integrate the newly developed GUI with the existing Python functions for collecting Incident Action Plan data and generating documents. This includes connecting GUI input fields to the `collect_iap_data` function, linking the "Generate IAP" button to the `generate_iap_document` function, and enabling the "Save IAP" button to use `save_iap_to_files` and `save_iap_to_pdf` based on the selected output format checkboxes.

## Integrate GUI with IAP Logic

### Subtask:
Connect the GUI elements to the existing Python functions for interactive data collection and document generation for both IAP types. Ensure that user inputs from the GUI populate the respective IAP data models and that the generated documents can be saved to selected formats (Markdown, Plain Text, PDF) through GUI actions, respecting the output format checkboxes.


**Reasoning**:
The subtask requires refactoring the GUI creation into a class and integrating it with the IAP generation and saving logic. I will begin by defining the `IAPGeneratorGUI` class, moving all existing GUI element creations into its `__init__` method, and making them instance attributes. I will also add a `tk.Text` widget for displaying the IAP content and connect the 'Generate IAP' button to a placeholder method for now, to ensure the basic class structure and GUI elements are correctly set up.



In [ ]:
import tkinter as tk
from tkinter import ttk, messagebox
import json
import datetime

# --- Re-importing all necessary functions from previous steps for completeness ---
# Helper functions for input (these will not be used by the GUI directly for input collection,
# but are kept here for the underlying IAP data model population logic if needed, or for console fallback)
def get_string_input(prompt, default=None):
    """Gets a string input from the user."""
    # This function is primarily for console input; GUI will use entry widgets.
    pass

def get_datetime_input(prompt, format_str, value_type="date"):
    """Gets a date or time input from the user with validation."""
    # This function is primarily for console input; GUI will use entry widgets.
    pass

def get_list_of_dicts_input(prompt_singular, field_definitions):
    """Collects multiple entries, each a dictionary, for a list type field."""
    # This function is primarily for console input; GUI will require more complex widgets.
    pass

def get_dict_input(prompt, field_definitions):
    """Collects fields for a dictionary type field."""
    # This function is primarily for console input; GUI will require more complex widgets.
    pass

# IAP Data Model (from previous step)
iap_data_model = {
    "Incident_Name": None,
    "Operational_Period": {
        "Start_Date": None,
        "End_Date": None,
        "Start_Time": None,
        "End_Time": None
    },
    "ICS_202_Incident_Objectives": {
        "Objectives": [],
        "General_Safety_Message": None,
        "Prepared_By": {
            "Name": None,
            "Position": None,
            "Signature": None
        },
        "Date": None,
        "Time": None
    },
    "ICS_203_Organization_Assignment_List": {
        "Incident_Commander": {
            "Name": None,
            "Agency": None,
            "Phone": None
        },
        "Section_Chiefs": {
            "Operations": {"Name": None, "Agency": None, "Phone": None},
            "Planning": {"Name": None, "Agency": None, "Phone": None},
            "Logistics": {"Name": None, "Agency": None, "Phone": None},
            "Finance_Admin": {"Name": None, "Agency": None, "Phone": None}
        },
        "Other_Positions": [] # List of dictionaries for other key positions
    },
    "ICS_204_Assignment_List": [
        # Each item in this list will be a dictionary representing one assignment
        {
            "Division_Group": None,
            "Branch": None,
            "Resources_Assigned": [], # List of dictionaries for resources (e.g., {'Name': 'Engine 1', 'Type': 'Fire Engine'})
            "Task_Activity": None,
            "Special_Instructions": None,
            "Reporting_Location": None,
            "Reporting_Time": None,
            "Supervisor": {"Name": None, "Contact": None}
        }
    ],
    "ICS_205_Incident_Radio_Communications_Plan": [
        # Each item in this list will be a dictionary representing one channel
        {
            "Channel_Name": None,
            "Function": None,
            "Assignment": None,
            "Frequency_Mode_Tone": None,
            "Remarks": None
        }
    ],
    "ICS_206_Medical_Plan": {
        "Medical_Aid_Stations": [],
        "Hospitals": [],
        "Ambulance_Services": [],
        "Medical_Emergency_Procedures": None
    },
    "Map_Diagram": {
        "Description": None,
        "File_Path": None # Placeholder for a file path or URL to a map/diagram
    },
    "Safety_Message_Plan": None # Could be a string or a more structured dictionary
}

def collect_iap_data(data_model):
    """Interactively collects Incident Action Plan data from the user."""
    # This is the console-based collection function, not used by the GUI directly
    pass

def generate_iap_document(iap_data):
    """Generates a formatted NIMS/ICS compliant Incident Action Plan document from collected data."""
    document_parts = []

    document_parts.append("# Incident Action Plan (IAP)\n")

    if iap_data.get("Incident_Name"):
        document_parts.append(f"## Incident Name: {iap_data['Incident_Name']}\n")

    # Operational Period
    op_period = iap_data.get("Operational_Period")
    if op_period and op_period.get("Start_Date"):
        document_parts.append("### 1. Operational Period\n")
        document_parts.append(f"* **Start:** {op_period.get('Start_Date')} {op_period.get('Start_Time')}\n")
        document_parts.append(f"* **End:** {op_period.get('End_Date')} {op_period.get('End_Time')}\n\n")

    # ICS 202 - Incident Objectives
    ics_202 = iap_data.get("ICS_202_Incident_Objectives")
    if ics_202 and (ics_202.get("Objectives") or ics_202.get("General_Safety_Message")):
        document_parts.append("### 2. ICS Form 202 - Incident Objectives\n")
        if ics_202.get("Objectives"):
            document_parts.append("#### Objectives:\n")
            for obj in ics_202["Objectives"]:
                document_parts.append(f"* {obj}\n")
        if ics_202.get("General_Safety_Message"):
            document_parts.append(f"#### General Safety Message:\n{ics_202['General_Safety_Message']}\n")
        if ics_202.get("Prepared_By") and ics_202["Prepared_By"].get("Name"):
            prep = ics_202["Prepared_By"]
            document_parts.append(f"* **Prepared By:** {prep.get('Name')} ({prep.get('Position')})\n")
            if prep.get('Signature'):
                document_parts.append(f"* **Signature:** {prep.get('Signature')}\n")
            document_parts.append(f"* **Date/Time:** {ics_202.get('Date')} {ics_202.get('Time')}\n\n")

    # ICS 203 - Organization Assignment List
    ics_203 = iap_data.get("ICS_203_Organization_Assignment_List")
    if ics_203 and (ics_203.get("Incident_Commander") or ics_203.get("Section_Chiefs") or ics_203.get("Other_Positions")):
        document_parts.append("### 3. ICS Form 203 - Organization Assignment List\n")
        if ics_203.get("Incident_Commander") and ics_203["Incident_Commander"].get("Name"):
            ic = ics_203["Incident_Commander"]
            document_parts.append(f"#### Incident Commander:\n")
            document_parts.append(f"* **Name:** {ic.get('Name')}\n")
            document_parts.append(f"* **Agency:** {ic.get('Agency')}\n")
            document_parts.append(f"* **Phone:** {ic.get('Phone')}\n\n")

        if ics_203.get("Section_Chiefs"):
            document_parts.append("#### Section Chiefs:\n")
            for section, details in ics_203["Section_Chiefs"].items():
                if details.get("Name"):
                    document_parts.append(f"* **{section.replace('_', ' ')}:** {details.get('Name')} ({details.get('Agency')}) - {details.get('Phone')}\n")
            document_parts.append("\n")

        if ics_203.get("Other_Positions"):
            document_parts.append("#### Other Key Positions:\n")
            for pos in ics_203["Other_Positions"]:
                if pos.get("Name"):
                    document_parts.append(f"* **{pos.get('Position')}:** {pos.get('Name')} ({pos.get('Agency')}) - {pos.get('Phone')}\n")
            document_parts.append("\n")

    # ICS 204 - Assignment List
    ics_204_list = iap_data.get("ICS_204_Assignment_List")
    if ics_204_list:
        document_parts.append("### 4. ICS Form 204 - Assignment List\n")
        for i, assignment in enumerate(ics_204_list):
            if assignment.get("Division_Group"):
                document_parts.append(f"#### Assignment {i+1}: {assignment.get('Division_Group')}\n")
                if assignment.get("Branch"):
                    document_parts.append(f"* **Branch:** {assignment.get('Branch')}\n")
                if assignment.get("Resources_Assigned"):
                    document_parts.append(f"* **Resources Assigned:** {', '.join(assignment['Resources_Assigned'])}\n")
                if assignment.get("Task_Activity"):
                    document_parts.append(f"* **Task/Activity:** {assignment.get('Task_Activity')}\n")
                if assignment.get("Special_Instructions"):
                    document_parts.append(f"* **Special Instructions:** {assignment.get('Special_Instructions')}\n")
                if assignment.get("Reporting_Location"):
                    document_parts.append(f"* **Reporting Location:** {assignment.get('Reporting_Location')}\n")
                if assignment.get("Reporting_Time"):
                    document_parts.append(f"* **Reporting Time:** {assignment.get('Reporting_Time')}\n")
                if assignment.get("Supervisor") and assignment["Supervisor"].get("Name"):
                    sup = assignment["Supervisor"]
                    document_parts.append(f"* **Supervisor:** {sup.get('Name')} ({sup.get('Contact')})\n")
                document_parts.append("\n")

    # ICS 205 - Incident Radio Communications Plan
    ics_205_list = iap_data.get("ICS_205_Incident_Radio_Communications_Plan")
    if ics_205_list:
        document_parts.append("### 5. ICS Form 205 - Incident Radio Communications Plan\n")
        for i, channel in enumerate(ics_205_list):
            if channel.get("Channel_Name"):
                document_parts.append(f"#### Channel {i+1}: {channel.get('Channel_Name')}\n")
                document_parts.append(f"* **Function:** {channel.get('Function')}\n")
                document_parts.append(f"* **Assignment:** {channel.get('Assignment')}\n")
                document_parts.append(f"* **Frequency/Mode/Tone:** {channel.get('Frequency_Mode_Tone')}\n")
                if channel.get("Remarks"):
                    document_parts.append(f"* **Remarks:** {channel.get('Remarks')}\n")
                document_parts.append("\n")

    # ICS 206 - Medical Plan
    ics_206 = iap_data.get("ICS_206_Medical_Plan")
    if ics_206 and (ics_206.get("Medical_Aid_Stations") or ics_206.get("Hospitals") or ics_206.get("Ambulance_Services") or ics_206.get("Medical_Emergency_Procedures")):
        document_parts.append("### 6. ICS Form 206 - Medical Plan\n")
        if ics_206.get("Medical_Aid_Stations"):
            document_parts.append("#### Medical Aid Stations:\n")
            for station in ics_206["Medical_Aid_Stations"]:
                if station.get("Name"):
                    document_parts.append(f"* **{station.get('Name')}:** {station.get('Location')} (Capabilities: {station.get('Capabilities')})\n")
            document_parts.append("\n")

        if ics_206.get("Hospitals"):
            document_parts.append("#### Hospitals:\n")
            for hospital in ics_206["Hospitals"]:
                if hospital.get("Name"):
                    specs = f" (Specializations: {hospital['Specializations']})" if hospital.get('Specializations') else ''
                    document_parts.append(f"* **{hospital.get('Name')}:** {hospital.get('Location')} (Contact: {hospital.get('Contact')}){specs}\n")
            document_parts.append("\n")

        if ics_206.get("Ambulance_Services"):
            document_parts.append("#### Ambulance Services:\n")
            for service in ics_206["Ambulance_Services"]:
                if service.get("Provider"):
                    ex_points = f" (Exchange Points: {service['Exchange_Points']})" if service.get('Exchange_Points') else ''
                    document_parts.append(f"* **{service.get('Provider')}:** Contact: {service.get('Contact')}{ex_points}\n")
            document_parts.append("\n")

        if ics_206.get("Medical_Emergency_Procedures"):
            document_parts.append(f"#### Medical Emergency Procedures:\n{ics_206['Medical_Emergency_Procedures']}\n\n")

    # Map/Diagram
    map_diag = iap_data.get("Map_Diagram")
    if map_diag and (map_diag.get("Description") or map_diag.get("File_Path")):
        document_parts.append("### 7. Map / Diagram\n")
        if map_diag.get("Description"):
            document_parts.append(f"* **Description:** {map_diag.get('Description')}\n")
        if map_diag.get("File_Path"):
            document_parts.append(f"* **File Path/URL:** {map_diag.get('File_Path')}\n")
        document_parts.append("\n")

    # Safety Message/Plan
    if iap_data.get("Safety_Message_Plan"):
        document_parts.append("### 8. Safety Message / Plan\n")
        document_parts.append(f"{iap_data['Safety_Message_Plan']}\n\n")

    return "".join(document_parts)

import markdown
from weasyprint import HTML
import os

def save_iap_to_files(formatted_iap_document, filename_prefix="incident_iap"):
    """Saves the formatted IAP document to Markdown and plain text files."""
    markdown_filename = f"{filename_prefix}.md"
    text_filename = f"{filename_prefix}.txt"

    try:
        with open(markdown_filename, "w", encoding="utf-8") as f:
            f.write(formatted_iap_document)
        print(f"IAP successfully saved to {markdown_filename}")

        with open(text_filename, "w", encoding="utf-8") as f:
            f.write(formatted_iap_document)
        print(f"IAP successfully saved to {text_filename}")
        return True
    except IOError as e:
        print(f"Error saving files: {e}")
        return False

def save_iap_to_pdf(formatted_iap_document, filename_prefix="incident_iap"):
    """Converts the Markdown formatted IAP document to HTML and then saves it as a PDF file."""
    pdf_filename = f"{filename_prefix}.pdf"

    try:
        html_content = markdown.markdown(formatted_iap_document)

        html_styled = f"""
<html>
<head>
    <meta charset=\"utf-8\">
    <title>{filename_prefix.replace('_', ' ').title()} IAP</title>
    <style>
        body {{ font-family: sans-serif; margin: 1in; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 0.5em; }}
        h2 {{ color: #34495e; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }}
        h3 {{ color: #34495e; margin-top: 1.5em; }}
        h4 {{ color: #34495e; margin-top: 1em; }}
        ul {{ list-style-type: disc; margin-left: 1.5em; }}
        li {{ margin-bottom: 0.5em; }}
        b {{ font-weight: bold; }}
    </style>
</head>
<body>
{html_content}
</body>
</html>
"""

        HTML(string=html_styled).write_pdf(pdf_filename)
        print(f"IAP successfully saved to {pdf_filename}")
        return True
    except Exception as e:
        print(f"Error saving PDF file: {e}")
        return False


class IAPGeneratorGUI:
    def __init__(self, master):
        self.master = master
        master.title("NIMS/ICS IAP Generator")

        self.iap_data_model = iap_data_model.copy() # Use the global data model as template
        self.generated_iap_content = "" # To store the generated IAP document string

        # Create a main frame for padding and organization
        main_frame = ttk.Frame(master, padding="10 10 10 10")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        master.columnconfigure(0, weight=1)
        master.rowconfigure(0, weight=1)

        # Incident Details
        incident_frame = ttk.LabelFrame(main_frame, text="Incident Details", padding="10 10 10 10")
        incident_frame.grid(row=0, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
        incident_frame.columnconfigure(1, weight=1)

        ttk.Label(incident_frame, text="Incident Name:").grid(row=0, column=0, sticky=tk.W, pady=2, padx=5)
        self.incident_name_entry = ttk.Entry(incident_frame, width=50)
        self.incident_name_entry.grid(row=0, column=1, sticky=(tk.W, tk.E), pady=2, padx=5)

        # Operational Period
        op_period_frame = ttk.LabelFrame(main_frame, text="Operational Period", padding="10 10 10 10")
        op_period_frame.grid(row=1, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
        op_period_frame.columnconfigure(1, weight=1)
        op_period_frame.columnconfigure(3, weight=1)

        ttk.Label(op_period_frame, text="Start Date (YYYY-MM-DD):").grid(row=0, column=0, sticky=tk.W, pady=2, padx=5)
        self.op_start_date_entry = ttk.Entry(op_period_frame, width=20)
        self.op_start_date_entry.grid(row=0, column=1, sticky=(tk.W, tk.E), pady=2, padx=5)

        ttk.Label(op_period_frame, text="End Date (YYYY-MM-DD):").grid(row=0, column=2, sticky=tk.W, pady=2, padx=5)
        self.op_end_date_entry = ttk.Entry(op_period_frame, width=20)
        self.op_end_date_entry.grid(row=0, column=3, sticky=(tk.W, tk.E), pady=2, padx=5)

        ttk.Label(op_period_frame, text="Start Time (HH:MM):").grid(row=1, column=0, sticky=tk.W, pady=2, padx=5)
        self.op_start_time_entry = ttk.Entry(op_period_frame, width=20)
        self.op_start_time_entry.grid(row=1, column=1, sticky=(tk.W, tk.E), pady=2, padx=5)

        ttk.Label(op_period_frame, text="End Time (HH:MM):").grid(row=1, column=2, sticky=tk.W, pady=2, padx=5)
        self.op_end_time_entry = ttk.Entry(op_period_frame, width=20)
        self.op_end_time_entry.grid(row=1, column=3, sticky=(tk.W, tk.E), pady=2, padx=5)

        # Placeholder for other IAP sections
        placeholder_frame = ttk.LabelFrame(main_frame, text="Other IAP Sections (Placeholders)", padding="10 10 10 10")
        placeholder_frame.grid(row=2, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
        ttk.Label(placeholder_frame, text="More input fields would go here for ICS 202, 203, 204, etc.").grid(row=0, column=0, sticky=tk.W, padx=5, pady=5)

        # Output Display Area
        output_frame = ttk.LabelFrame(main_frame, text="Generated IAP Document", padding="10 10 10 10")
        output_frame.grid(row=3, column=0, columnspan=2, sticky=(tk.W, tk.E, tk.N, tk.S), pady=5)
        output_frame.columnconfigure(0, weight=1)
        output_frame.rowconfigure(0, weight=1)

        self.iap_display_text = tk.Text(output_frame, wrap=tk.WORD, height=15, width=80)
        self.iap_display_text.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S), padx=5, pady=5)
        # Add scrollbar
        scrollbar = ttk.Scrollbar(output_frame, orient=tk.VERTICAL, command=self.iap_display_text.yview)
        scrollbar.grid(row=0, column=1, sticky=(tk.N, tk.S))
        self.iap_display_text['yscrollcommand'] = scrollbar.set

        # Buttons for actions
        button_frame = ttk.Frame(main_frame, padding="5 0 5 0")
        button_frame.grid(row=4, column=0, sticky=(tk.W, tk.E), pady=10)
        button_frame.columnconfigure(0, weight=1)
        button_frame.columnconfigure(1, weight=1)
        button_frame.columnconfigure(2, weight=1)

        generate_button = ttk.Button(button_frame, text="Generate IAP", command=self.generate_iap) # Connect to method
        generate_button.grid(row=0, column=0, padx=5)

        save_button = ttk.Button(button_frame, text="Save IAP", command=self.save_iap) # Connect to method
        save_button.grid(row=0, column=1, padx=5)

        exit_button = ttk.Button(button_frame, text="Exit", command=master.destroy)
        exit_button.grid(row=0, column=2, padx=5)

        # Options for output format selection
        output_format_frame = ttk.LabelFrame(main_frame, text="Output Formats", padding="10 10 10 10")
        output_format_frame.grid(row=4, column=1, sticky=(tk.E), pady=10, padx=5)

        # Variables to hold checkbox states
        self.md_var = tk.BooleanVar(value=True)
        self.txt_var = tk.BooleanVar(value=True)
        self.pdf_var = tk.BooleanVar(value=True)

        ttk.Checkbutton(output_format_frame, text="Markdown (.md)", variable=self.md_var).grid(row=0, column=0, sticky=tk.W, padx=2)
        ttk.Checkbutton(output_format_frame, text="Plain Text (.txt)", variable=self.txt_var).grid(row=1, column=0, sticky=tk.W, padx=2)
        ttk.Checkbutton(output_format_frame, text="PDF (.pdf)", variable=self.pdf_var).grid(row=2, column=0, sticky=tk.W, padx=2)

    def populate_iap_data_from_gui(self):
        """Reads data from GUI input fields and populates a partial IAP data model."""
        gui_iap_data = self.iap_data_model.copy() # Start with a fresh copy of the model

        # Incident Name
        gui_iap_data["Incident_Name"] = self.incident_name_entry.get()

        # Operational Period
        gui_iap_data["Operational_Period"]["Start_Date"] = self.op_start_date_entry.get()
        gui_iap_data["Operational_Period"]["End_Date"] = self.op_end_date_entry.get()
        gui_iap_data["Operational_Period"]["Start_Time"] = self.op_start_time_entry.get()
        gui_iap_data["Operational_Period"]["End_Time"] = self.op_end_time_entry.get()

        # Placeholder for other data that would be collected from more GUI elements

        return gui_iap_data

    def generate_iap(self):
        """Generates the IAP document based on GUI inputs and displays it."""
        print("Generate IAP button clicked") # For debugging
        iap_data_from_gui = self.populate_iap_data_from_gui()

        # Validate basic date/time inputs before generating
        try:
            if iap_data_from_gui["Operational_Period"]["Start_Date"]:
                datetime.datetime.strptime(iap_data_from_gui["Operational_Period"]["Start_Date"], '%Y-%m-%d')
            if iap_data_from_gui["Operational_Period"]["End_Date"]:
                datetime.datetime.strptime(iap_data_from_gui["Operational_Period"]["End_Date"], '%Y-%m-%d')
            if iap_data_from_gui["Operational_Period"]["Start_Time"]:
                datetime.datetime.strptime(iap_data_from_gui["Operational_Period"]["Start_Time"], '%H:%M')
            if iap_data_from_gui["Operational_Period"]["End_Time"]:
                datetime.datetime.strptime(iap_data_from_gui["Operational_Period"]["End_Time"], '%H:%M')
        except ValueError:
            messagebox.showerror("Input Error", "Invalid Date or Time format. Please use YYYY-MM-DD for dates and HH:MM for times.")
            return

        self.generated_iap_content = generate_iap_document(iap_data_from_gui)

        self.iap_display_text.delete(1.0, tk.END) # Clear previous content
        self.iap_display_text.insert(tk.END, self.generated_iap_content)
        messagebox.showinfo("Success", "IAP Document Generated and displayed.")


    def save_iap(self):
        """Saves the generated IAP document to selected formats."""
        print("Save IAP button clicked") # For debugging
        if not self.generated_iap_content:
            messagebox.showwarning("No IAP Generated", "Please generate the IAP document first before saving.")
            return

        filename_prefix = self.incident_name_entry.get().replace(" ", "_") if self.incident_name_entry.get() else "incident_iap"
        filename_prefix = filename_prefix.lower()

        save_successful = False
        if self.md_var.get():
            if save_iap_to_files(self.generated_iap_content, filename_prefix=filename_prefix):
                save_successful = True
            else:
                messagebox.showerror("Save Error", "Failed to save Markdown/Text file(s).")

        if self.pdf_var.get():
            if save_iap_to_pdf(self.generated_iap_content, filename_prefix=filename_prefix):
                save_successful = True
            else:
                messagebox.showerror("Save Error", "Failed to save PDF file.")

        if save_successful:
            messagebox.showinfo("Save Status", f"IAP saved successfully to {filename_prefix}.md, {filename_prefix}.txt and/or {filename_prefix}.pdf")

# --- Main execution block ---
if __name__ == "__main__":
    root = tk.Tk()
    app = IAPGeneratorGUI(root)
    root.mainloop()

print("GUI Application setup complete. Interact with the opened window.")